import Foundation

enum L10n {
    private static let langKey = "LAUNCHER_LANGUAGE"

    static var current: String = {
        if let saved = UserDefaults.standard.string(forKey: langKey),
           supportedLanguages.contains(saved) {
            return saved
        }
        let preferred = Locale.preferredLanguages.first ?? "en"
        let code = String(preferred.prefix(2))
        return supportedLanguages.contains(code) ? code : "en"
    }()

    static func setCurrent(_ lang: String) {
        guard supportedLanguages.contains(lang) else { return }
        current = lang
        UserDefaults.standard.set(lang, forKey: langKey)
    }

    static let supportedLanguages = [
        "en", "ru", "uk", "ar", "kk", "vi", "pl", "de", "es", "tr", "zh", "hi"
    ]

    static let languageNames: [String: String] = [
        "en": "English",
        "ru": "Русский",
        "uk": "Українська",
        "ar": "العربية",
        "kk": "Қазақша",
        "vi": "Tiếng Việt",
        "pl": "Polski",
        "de": "Deutsch",
        "es": "Español",
        "tr": "Türkçe",
        "zh": "中文",
        "hi": "हिन्दी"
    ]

    private static func resolve(_ key: String) -> String {
        translations[current]?[key]
            ?? translations["en"]?[key]
            ?? key
    }

    static let app = App()
    static let tab = Tab()
    static let steam = Steam()
    static let local = Local()
    static let action = Action()
    static let alerts = Alerts()
    static let update = Update()
    static let footer = Footer()
    static let patch = Patch()
    static let folder = Folder()
    static let settings = Settings()
    static let about = About()
    static let mod = Mod()
    static let sidebar = Sidebar()

    struct App {
        var title: String { resolve("app.title") }
        var subtitle: String { resolve("app.subtitle") }
    }

    struct Tab {
        var steam: String { resolve("tab.steam") }
        var local: String { resolve("tab.local") }
    }

    struct Steam {
        var credentials: String { resolve("steam.credentials") }
        var submit: String { resolve("steam.submit") }
        var cancel: String { resolve("steam.cancel") }
        var download: String { resolve("steam.download") }
        var usernamePlaceholder: String { resolve("steam.usernamePlaceholder") }
        var passwordPlaceholder: String { resolve("steam.passwordPlaceholder") }
        var storedPasswordHint: String { resolve("steam.storedPasswordHint") }
        var storedPasswordTitle: String { resolve("steam.storedPasswordTitle") }
        var storedPasswordMsg: String { resolve("steam.storedPasswordMsg") }
        var storedPasswordUse: String { resolve("steam.storedPasswordUse") }
        var storedPasswordType: String { resolve("steam.storedPasswordType") }
        let status = SteamStatus()
    }

    struct SteamStatus {
        var ready: String { resolve("steam.status.ready") }
        var installingSteamCMD: String { resolve("steam.status.installingSteamCMD") }
        var awaitingCreds: String { resolve("steam.status.awaitingCreds") }
        var authenticating: String { resolve("steam.status.authenticating") }
        var steamGuard: String { resolve("steam.status.steamGuard") }
        var downloading: String { resolve("steam.status.downloading") }
        var validating: String { resolve("steam.status.validating") }
        var downloadingPatch: String { resolve("steam.status.downloadingPatch") }
        var unpacking: String { resolve("steam.status.unpacking") }
        var assetsReady: String { resolve("steam.status.assetsReady") }
        var error: String { resolve("steam.status.error") }
    }

    struct Local {
        var path: String { resolve("local.path") }
        var locate: String { resolve("local.locate") }
        var selectHint: String { resolve("local.selectHint") }
        var invalidTarget: String { resolve("local.invalidTarget") }
    }

    struct Action {
        var launch: String { resolve("action.launch") }
        var patch: String { resolve("action.patch") }
        var initialize: String { resolve("action.init") }
    }

    struct Alerts {
        var launchError: String { resolve("alert.launchError") }
        var ok: String { resolve("alert.ok") }
        var gameNotFound: String { resolve("alert.gameNotFound") }
        var gameNotFoundMsg: String { resolve("alert.gameNotFoundMsg") }
        var openSteamStore: String { resolve("alert.openSteamStore") }
        var close: String { resolve("alert.close") }
        var patchTitle: String { resolve("alert.patchTitle") }
        var patchMsg: String { resolve("alert.patchMsg") }
        var patchButton: String { resolve("alert.patchButton") }
        var folderNotSelected: String { resolve("alert.folderNotSelected") }
        var binaryNotFound: String { resolve("alert.binaryNotFound") }
        var modFolderMissing: String { resolve("alert.modFolderMissing") }
        var modConfigMissing: String { resolve("alert.modConfigMissing") }
        var launchFailed: String { resolve("alert.launchFailed") }
        var cancel: String { resolve("alert.cancel") }
    }

    struct Mod {
        var section: String { resolve("mod.section") }
        var install: String { resolve("mod.install") }
        var repair: String { resolve("mod.repair") }
        var installed: String { resolve("mod.installed") }
        var reinstall: String { resolve("mod.reinstall") }
        var remove: String { resolve("mod.remove") }
        var installingTitle: String { resolve("mod.installingTitle") }
        var removingTitle: String { resolve("mod.removingTitle") }
        var installingHint: String { resolve("mod.installingHint") }
        var damaged: String { resolve("mod.damaged") }
        var sizeInfo: String { resolve("mod.sizeInfo") }
        var sizeParts: String { resolve("mod.sizeParts") }
        var confirmReinstallTitle: String { resolve("mod.confirmReinstallTitle") }
        var confirmReinstallMsg: String { resolve("mod.confirmReinstallMsg") }
        var confirmRemoveTitle: String { resolve("mod.confirmRemoveTitle") }
        var confirmRemoveMsg: String { resolve("mod.confirmRemoveMsg") }
        let status = ModStatus()
    }

    struct ModStatus {
        var notInstalled: String { resolve("mod.status.notInstalled") }
        var downloading: String { resolve("mod.status.downloading") }
        var downloadingPart: String { resolve("mod.status.downloadingPart") }
        var unpacking: String { resolve("mod.status.unpacking") }
        var removing: String { resolve("mod.status.removing") }
        var unpackingPart: String { resolve("mod.status.unpackingPart") }
        var installed: String { resolve("mod.status.installed") }
        var error: String { resolve("mod.status.error") }
    }

    struct Sidebar {
        var reset: String { resolve("sidebar.reset") }
    }

    struct Update {
        var available: String { resolve("update.available") }
        var download: String { resolve("update.download") }
        var details: String { resolve("update.details") }
    }

    struct Footer {
        var author: String { resolve("footer.author") }
    }

    struct Patch {
        let status = PatchStatus()
    }

    struct PatchStatus {
        var idle: String { resolve("patch.status.idle") }
        var cleaning: String { resolve("patch.status.cleaning") }
        var downloading: String { resolve("patch.status.downloading") }
        var unpacking: String { resolve("patch.status.unpacking") }
        var completed: String { resolve("patch.status.completed") }
        var error: String { resolve("patch.status.error") }
    }

    struct Folder {
        var prompt: String { resolve("folder.prompt") }
    }

    struct Settings {
        var title: String { resolve("settings.title") }
        var windowedEdgeScroll: String { resolve("settings.windowedEdgeScroll") }
        var windowedEdgeScrollDesc: String { resolve("settings.windowedEdgeScrollDesc") }
        var language: String { resolve("settings.language") }
        var about: String { resolve("settings.about") }
        var aboutButton: String { resolve("settings.aboutButton") }
        var cameraSection: String { resolve("settings.cameraSection") }
        var interfaceSection: String { resolve("settings.interfaceSection") }
        var showHotkeyLabels: String { resolve("settings.showHotkeyLabels") }
        var showHotkeyLabelsDesc: String { resolve("settings.showHotkeyLabelsDesc") }
        var cameraMaxHeight: String { resolve("settings.cameraMaxHeight") }
        var cameraMinHeight: String { resolve("settings.cameraMinHeight") }
        var cameraSpeed: String { resolve("settings.cameraSpeed") }
        var fpsSection: String { resolve("settings.fpsSection") }
        var statsOverlay: String { resolve("settings.statsOverlay") }
        var limitFps: String { resolve("settings.limitFps") }
        var networkSection: String { resolve("settings.networkSection") }
        var altEndpoint: String { resolve("settings.altEndpoint") }
        var verboseLogging: String { resolve("settings.verboseLogging") }
        var shareLogs: String { resolve("settings.shareLogs") }
        var shareLogsHint: String { resolve("settings.shareLogsHint") }
        var shareLogsNone: String { resolve("settings.shareLogsNone") }
        var shareLogsFailed: String { resolve("settings.shareLogsFailed") }
        var gameLanguage: String { resolve("settings.gameLanguage") }
        var gameLanguageRestart: String { resolve("settings.gameLanguageRestart") }
        
        var scopeGlobal: String { resolve("settings.scope.global") }
        var scopeOnline: String { resolve("settings.scope.online") }
        var scopeLobbyHost: String { resolve("settings.scope.lobbyHost") }
        var scopeGlobalDesc: String { resolve("settings.scope.globalDesc") }
        var scopeOnlineDesc: String { resolve("settings.scope.onlineDesc") }
        var scopeLobbyHostDesc: String { resolve("settings.scope.lobbyHostDesc") }
        var legendSection: String { resolve("settings.legendSection") }
    }

    struct About {
        var windowTitle: String { resolve("about.windowTitle") }
        var nativePort: String { resolve("about.nativePort") }
        var portAuthor: String { resolve("about.portAuthor") }
        var builtOnTop: String { resolve("about.builtOnTop") }
        var website: String { resolve("about.website") }
        var legal: String { resolve("about.legal") }
        var version: String { resolve("about.version") }
    }

    static let translations: [String: [String: String]] = [
        "en": en, "ru": ru, "uk": uk, "ar": ar, "kk": kk,
        "vi": vi, "pl": pl, "de": de, "es": es, "tr": tr,
        "zh": zh, "hi": hi
    ]

    static let en: [String: String] = [
        "app.title": "GENERALS ONLINE",
        "app.subtitle": "COMMUNITY MAC PORT",
        "tab.steam": "STEAM (RECOMMENDED)",
        "tab.local": "LOCAL ARCHIVE",
        "steam.credentials": "STEAM CREDENTIALS",
        "steam.submit": "SUBMIT",
        "steam.cancel": "CANCEL",
        "steam.download": "DOWNLOAD ASSETS",
        "local.path": "TACTICAL DATA PATH:",
        "local.locate": "LOCATE",
        "local.selectHint": "SELECT THE PARENT DIRECTORY CONTAINING BOTH GAME VERSIONS",
        "local.invalidTarget": "INVALID TARGET — No ini.big / inizh.big detected in subdirectories",
        "action.launch": "LAUNCH",
        "action.patch": "PATCH",
        "action.init": "INITIALIZING...",
        "alert.launchError": "Launch Error",
        "alert.ok": "OK",
        "alert.gameNotFound": "Game Not Found",
        "alert.gameNotFoundMsg": "The account \"%@\" does not own Command & Conquer™ Generals — Zero Hour.\n\nPurchase the game on Steam, then press \"Download Assets\" again.",
        "alert.openSteamStore": "Open Steam Store",
        "alert.close": "Close",
        "alert.patchTitle": "Apply Community Patch?",
        "alert.patchMsg": "Your game files may be irreversibly modified or deleted.\nThis is required to play online.",
        "alert.patchButton": "Patch",
        "update.available": "UPDATE AVAILABLE: v%@",
        "update.download": "DOWNLOAD UPDATE",
        "update.details": "SEE DETAILS",
        "footer.author": "Ported by OKJI (Okladnoj)",
        "steam.status.ready": "READY",
        "steam.status.installingSteamCMD": "INSTALLING STEAMCMD...",
        "steam.status.awaitingCreds": "AWAITING CREDENTIALS",
        "steam.status.authenticating": "AUTHENTICATING...",
        "steam.status.steamGuard": "STEAM GUARD CODE REQUIRED",
        "steam.status.downloading": "DOWNLOADING ASSETS... %@",
        "steam.status.validating": "VALIDATING FILES...",
        "steam.status.downloadingPatch": "DOWNLOADING PATCH... %.0f%%",
        "steam.status.unpacking": "UNPACKING PATCH...",
        "steam.status.assetsReady": "ASSETS READY",
        "steam.status.error": "ERROR: %@",
        "patch.status.idle": "AWAITING ACTION",
        "patch.status.cleaning": "CLEANING CONFLICTING FILES...",
        "patch.status.downloading": "DOWNLOADING PATCH... %.0f%%",
        "patch.status.unpacking": "UNPACKING PATCH...",
        "patch.status.completed": "PATCH APPLIED SUCCESSFULLY",
        "patch.status.error": "ERROR: %@",
        "folder.prompt": "Select the Windows Game Folder (containing .big files)",
        "settings.title": "GAME SETTINGS",
        "settings.windowedEdgeScroll": "Edge Scroll in Windowed Mode",
        "settings.windowedEdgeScrollDesc": "Captures mouse cursor inside the game window during gameplay for edge scrolling.",
        "settings.language": "Language",
        "settings.about": "System",
        "settings.aboutButton": "About Generals Online",
        "settings.cameraSection": "Camera",
        "settings.interfaceSection": "Interface",
        "settings.showHotkeyLabels": "Show Hotkey Labels",
        "settings.showHotkeyLabelsDesc": "Displays each command's hotkey letter on its command-bar icon.",
        "settings.cameraMaxHeight": "Max Height (Zoom)",
        "settings.cameraMinHeight": "Min Height (Close)",
        "settings.cameraSpeed": "Camera Speed",
        "settings.fpsSection": "Performance",
        "settings.statsOverlay": "Show FPS & Ping Overlay",
        "settings.limitFps": "Limit Framerate",
        "settings.networkSection": "Network & Logs",
        "settings.altEndpoint": "Use Alternative Endpoint",
        "settings.verboseLogging": "Verbose Engine Logging",
        "settings.shareLogs": "Share Logs",
        "settings.shareLogsHint": "Opens the Telegram chat and the ZIP — drag it into the chat",
        "settings.shareLogsNone": "No log files found yet. Enable Verbose Engine Logging, run the game once, then try again.",
        "settings.shareLogsFailed": "Could not package the logs. Please try again.",
        "settings.gameLanguage": "Game Language",
        "settings.gameLanguageRestart": "Requires game restart",
        "settings.scope.global": "GLOBAL",
        "settings.scope.online": "ONLINE",
        "settings.scope.lobbyHost": "LOBBY HOST",
        "settings.scope.globalDesc": "GLOBAL: Applies to all game modes (Singleplayer, Skirmish, and Online).",
        "settings.scope.onlineDesc": "ONLINE: Only works in multiplayer network modes.",
        "settings.scope.lobbyHostDesc": "LOBBY HOST: Only applies when hosting multiplayer lobbies.",
        "settings.legendSection": "LEGEND",
        "about.windowTitle": "About Generals Online",
        "about.nativePort": "macOS Native Port",
        "about.portAuthor": "macOS Port by Dima Ok (OKJI)",
        "about.builtOnTop": "Built on top of the EA GPLv3 open-source release",
        "about.website": "Website",
        "about.legal": "C&C: Generals Zero Hour™ is a trademark of Electronic Arts.\nGame engine source code licensed under GPLv3.",
        "mod.section": "MODS",
        "mod.install": "INSTALL",
        "mod.repair": "REPAIR",
        "mod.installed": "%@ installed",
        "mod.reinstall": "Reinstall",
        "mod.remove": "Remove",
        "mod.installingTitle": "INSTALLING %@ — PLEASE WAIT",
        "mod.installingHint": "Your games are fine — launching and patching stay locked so the download is not interrupted",
        "mod.damaged": "%d file(s) missing — reinstall to repair",
        "mod.sizeInfo": "download %@ · disk %@",
        "mod.sizeParts": " · %d parts",
        "mod.status.notInstalled": "Not installed",
        "mod.status.downloading": "Downloading — %d%%",
        "mod.status.downloadingPart": "Downloading part %d of %d — %d%%",
        "mod.status.unpacking": "Unpacking",
        "mod.status.unpackingPart": "Unpacking part %d of %d",
        "mod.status.installed": "Installed",
        "mod.status.error": "Error: %@",
        "alert.folderNotSelected": "Game folder is not selected yet.",
        "alert.binaryNotFound": "%@ binary not found at %@",
        "alert.modFolderMissing": "Mod folder is not available.",
        "alert.modConfigMissing": "%@ is missing %@.",
        "alert.launchFailed": "Failed to launch game: %@",
        "sidebar.reset": "RESET",
        "about.version": "Version %@",
        "mod.confirmReinstallTitle": "Reinstall %@?",
        "mod.confirmReinstallMsg": "The installed files will be deleted first and downloaded again (%@).",
        "mod.confirmRemoveTitle": "Remove %@?",
        "mod.confirmRemoveMsg": "All installed files of this mod will be deleted.",
        "alert.cancel": "Cancel",
        "mod.status.removing": "Removing",
        "mod.removingTitle": "REMOVING %@ — PLEASE WAIT",
        "steam.storedPasswordHint": "Click to fill in the password saved in your keychain",
        "steam.usernamePlaceholder": "Steam login",
        "steam.passwordPlaceholder": "Enter password...",
        "steam.storedPasswordTitle": "Saved password found",
        "steam.storedPasswordMsg": "A password for “%@” is stored in your keychain. Use it, or type a new one?",
        "steam.storedPasswordUse": "Use saved",
        "steam.storedPasswordType": "Type manually"
    ]

    static let ru: [String: String] = [
        "app.title": "GENERALS ONLINE",
        "app.subtitle": "MAC ПОРТ ОТ СООБЩЕСТВА",
        "tab.steam": "STEAM (РЕКОМЕНДУЕТСЯ)",
        "tab.local": "ЛОКАЛЬНЫЙ АРХИВ",
        "steam.credentials": "УЧЁТНЫЕ ДАННЫЕ STEAM",
        "steam.submit": "ВОЙТИ",
        "steam.cancel": "ОТМЕНА",
        "steam.download": "ЗАГРУЗИТЬ РЕСУРСЫ",
        "local.path": "ПУТЬ К ДАННЫМ ИГРЫ:",
        "local.locate": "ВЫБРАТЬ",
        "local.selectHint": "УКАЖИТЕ РОДИТЕЛЬСКУЮ ПАПКУ С ОБЕИМИ ВЕРСИЯМИ ИГРЫ",
        "local.invalidTarget": "НЕВЕРНАЯ ЦЕЛЬ — ini.big / inizh.big не найдены в подкаталогах",
        "action.launch": "ЗАПУСК",
        "action.patch": "ПАТЧ",
        "action.init": "ИНИЦИАЛИЗАЦИЯ...",
        "alert.launchError": "Ошибка запуска",
        "alert.ok": "OK",
        "alert.gameNotFound": "Игра не найдена",
        "alert.gameNotFoundMsg": "Аккаунт «%@» не владеет Command & Conquer™ Generals — Zero Hour.\n\nКупите игру в Steam и нажмите «Загрузить ресурсы» ещё раз.",
        "alert.openSteamStore": "Открыть Steam",
        "alert.close": "Закрыть",
        "alert.patchTitle": "Применить Community Patch?",
        "alert.patchMsg": "Ваши файлы игры могут быть необратимо изменены или удалены.\nЭто необходимо для онлайн-игры.",
        "alert.patchButton": "Патч",
        "update.available": "ДОСТУПНО ОБНОВЛЕНИЕ: v%@",
        "update.download": "СКАЧАТЬ ОБНОВЛЕНИЕ",
        "update.details": "ПОДРОБНЕЕ",
        "footer.author": "Портировал OKJI (Okladnoj)",
        "steam.status.ready": "ГОТОВО",
        "steam.status.installingSteamCMD": "УСТАНОВКА STEAMCMD...",
        "steam.status.awaitingCreds": "ОЖИДАНИЕ УЧЁТНЫХ ДАННЫХ",
        "steam.status.authenticating": "АУТЕНТИФИКАЦИЯ...",
        "steam.status.steamGuard": "ТРЕБУЕТСЯ КОД STEAM GUARD",
        "steam.status.downloading": "ЗАГРУЗКА РЕСУРСОВ... %@",
        "steam.status.validating": "ПРОВЕРКА ФАЙЛОВ...",
        "steam.status.downloadingPatch": "ЗАГРУЗКА ПАТЧА... %.0f%%",
        "steam.status.unpacking": "РАСПАКОВКА ПАТЧА...",
        "steam.status.assetsReady": "РЕСУРСЫ ГОТОВЫ",
        "steam.status.error": "ОШИБКА: %@",
        "patch.status.idle": "ОЖИДАНИЕ ДЕЙСТВИЯ",
        "patch.status.cleaning": "ОЧИСТКА КОНФЛИКТУЮЩИХ ФАЙЛОВ...",
        "patch.status.downloading": "ЗАГРУЗКА ПАТЧА... %.0f%%",
        "patch.status.unpacking": "РАСПАКОВКА ПАТЧА...",
        "patch.status.completed": "ПАТЧ УСПЕШНО ПРИМЕНЁН",
        "patch.status.error": "ОШИБКА: %@",
        "folder.prompt": "Выберите папку с Windows-версией игры (содержащую .big файлы)",
        "settings.title": "НАСТРОЙКИ ИГРЫ",
        "settings.windowedEdgeScroll": "Автоскролл в оконном режиме",
        "settings.windowedEdgeScrollDesc": "Захватывает курсор мыши внутри окна игры во время матча для скролла карты.",
        "settings.language": "Язык",
        "settings.about": "Система",
        "settings.aboutButton": "О программе",
        "settings.cameraSection": "Камера",
        "settings.interfaceSection": "Интерфейс",
        "settings.showHotkeyLabels": "Показывать буквы хоткеев",
        "settings.showHotkeyLabelsDesc": "Отображает букву горячей клавиши на иконке команды в панели.",
        "settings.cameraMaxHeight": "Макс. высота (Зум)",
        "settings.cameraMinHeight": "Мин. высота (Приближение)",
        "settings.cameraSpeed": "Скорость камеры",
        "settings.fpsSection": "Производительность",
        "settings.statsOverlay": "Показывать оверлей FPS и Ping",
        "settings.limitFps": "Ограничить частоту кадров",
        "settings.networkSection": "Сеть и логи",
        "settings.altEndpoint": "Альтернативный сервер",
        "settings.verboseLogging": "Детальное логирование движка",
        "settings.shareLogs": "Отправить логи",
        "settings.shareLogsHint": "Откроет чат Telegram и ZIP — перетащи его в чат",
        "settings.shareLogsNone": "Логи ещё не найдены. Включите «Детальное логирование движка», запустите игру один раз и повторите.",
        "settings.shareLogsFailed": "Не удалось упаковать логи. Попробуйте ещё раз.",
        "settings.gameLanguage": "Язык игры",
        "settings.gameLanguageRestart": "Требуется перезапуск игры",
        "settings.scope.global": "ГЛОБАЛЬНО",
        "settings.scope.online": "ОНЛАЙН",
        "settings.scope.lobbyHost": "ХОСТ ЛОББИ",
        "settings.scope.globalDesc": "ГЛОБАЛЬНО: Применяется ко всем игровым режимам (Кампания, Сражение, Онлайн).",
        "settings.scope.onlineDesc": "ОНЛАЙН: Работает только в сетевых режимах игры.",
        "settings.scope.lobbyHostDesc": "ХОСТ ЛОББИ: Применяется только при создании сетевой игры (хостинге лобби).",
        "settings.legendSection": "ЛЕГЕНДА",
        "about.windowTitle": "О Generals Online",
        "about.nativePort": "Нативный порт для macOS",
        "about.portAuthor": "Порт для macOS: Дима Ок (OKJI)",
        "about.builtOnTop": "Разработано на базе открытого исходного кода EA GPLv3",
        "about.website": "Сайт",
        "about.legal": "C&C: Generals Zero Hour™ является товарным знаком Electronic Arts.\nИсходный код игрового движка лицензирован под GPLv3.",
        "mod.section": "МОДЫ",
        "mod.install": "УСТАНОВИТЬ",
        "mod.repair": "ВОССТАНОВИТЬ",
        "mod.installed": "%@ установлен",
        "mod.reinstall": "Переустановить",
        "mod.remove": "Удалить",
        "mod.installingTitle": "УСТАНОВКА %@ — ПОДОЖДИТЕ",
        "mod.installingHint": "С играми всё в порядке — запуск и патч заблокированы, чтобы не прервать загрузку",
        "mod.damaged": "Не хватает файлов: %d — переустановите для восстановления",
        "mod.sizeInfo": "загрузка %@ · диск %@",
        "mod.sizeParts": " · частей: %d",
        "mod.status.notInstalled": "Не установлен",
        "mod.status.downloading": "Загрузка — %d%%",
        "mod.status.downloadingPart": "Загрузка части %d из %d — %d%%",
        "mod.status.unpacking": "Распаковка",
        "mod.status.unpackingPart": "Распаковка части %d из %d",
        "mod.status.installed": "Установлен",
        "mod.status.error": "Ошибка: %@",
        "alert.folderNotSelected": "Папка с игрой ещё не выбрана.",
        "alert.binaryNotFound": "Исполняемый файл %@ не найден: %@",
        "alert.modFolderMissing": "Папка мода недоступна.",
        "alert.modConfigMissing": "У %@ отсутствует %@.",
        "alert.launchFailed": "Не удалось запустить игру: %@",
        "sidebar.reset": "СБРОС",
        "about.version": "Версия %@",
        "mod.confirmReinstallTitle": "Переустановить %@?",
        "mod.confirmReinstallMsg": "Установленные файлы сначала будут удалены и загружены заново (%@).",
        "mod.confirmRemoveTitle": "Удалить %@?",
        "mod.confirmRemoveMsg": "Все установленные файлы этого мода будут удалены.",
        "alert.cancel": "Отмена",
        "mod.status.removing": "Удаление",
        "mod.removingTitle": "УДАЛЕНИЕ %@ — ПОДОЖДИТЕ",
        "steam.storedPasswordHint": "Нажмите, чтобы подставить пароль из связки ключей",
        "steam.usernamePlaceholder": "Логин Steam",
        "steam.passwordPlaceholder": "Введите пароль...",
        "steam.storedPasswordTitle": "Найден сохранённый пароль",
        "steam.storedPasswordMsg": "Для «%@» в связке ключей есть пароль. Подставить его или ввести новый?",
        "steam.storedPasswordUse": "Подставить",
        "steam.storedPasswordType": "Ввести вручную"
    ]

    static let uk: [String: String] = [
        "app.title": "GENERALS ONLINE",
        "app.subtitle": "MAC ПОРТ ВІД СПІЛЬНОТИ",
        "tab.steam": "STEAM (РЕКОМЕНДОВАНО)",
        "tab.local": "ЛОКАЛЬНИЙ АРХІВ",
        "steam.credentials": "ОБЛІКОВІ ДАНІ STEAM",
        "steam.submit": "УВІЙТИ",
        "steam.cancel": "СКАСУВАТИ",
        "steam.download": "ЗАВАНТАЖИТИ РЕСУРСИ",
        "local.path": "ШЛЯХ ДО ДАНИХ ГРИ:",
        "local.locate": "ВИБРАТИ",
        "local.selectHint": "ВКАЖІТЬ БАТЬКІВСЬКУ ПАПКУ З ОБОМА ВЕРСІЯМИ ГРИ",
        "local.invalidTarget": "НЕПРАВИЛЬНА ЦІЛЬ — ini.big / inizh.big не знайдено в підкаталогах",
        "action.launch": "ЗАПУСК",
        "action.patch": "ПАТЧ",
        "action.init": "ІНІЦІАЛІЗАЦІЯ...",
        "alert.launchError": "Помилка запуску",
        "alert.ok": "OK",
        "alert.gameNotFound": "Гру не знайдено",
        "alert.gameNotFoundMsg": "Акаунт «%@» не володіє Command & Conquer™ Generals — Zero Hour.\n\nПридбайте гру в Steam та натисніть «Завантажити ресурси» ще раз.",
        "alert.openSteamStore": "Відкрити Steam",
        "alert.close": "Закрити",
        "alert.patchTitle": "Застосувати Community Patch?",
        "alert.patchMsg": "Ваші файли гри можуть бути безповоротно змінені або видалені.\nЦе необхідно для онлайн-гри.",
        "alert.patchButton": "Патч",
        "update.available": "ДОСТУПНЕ ОНОВЛЕННЯ: v%@",
        "update.download": "ЗАВАНТАЖИТИ ОНОВЛЕННЯ",
        "update.details": "ДЕТАЛЬНІШЕ",
        "footer.author": "Портував OKJI (Okladnoj)",
        "steam.status.ready": "ГОТОВО",
        "steam.status.installingSteamCMD": "ВСТАНОВЛЕННЯ STEAMCMD...",
        "steam.status.awaitingCreds": "ОЧІКУВАННЯ ОБЛІКОВИХ ДАНИХ",
        "steam.status.authenticating": "АУТЕНТИФІКАЦІЯ...",
        "steam.status.steamGuard": "ПОТРІБЕН КОД STEAM GUARD",
        "steam.status.downloading": "ЗАВАНТАЖЕННЯ РЕСУРСІВ... %@",
        "steam.status.validating": "ПЕРЕВІРКА ФАЙЛІВ...",
        "steam.status.downloadingPatch": "ЗАВАНТАЖЕННЯ ПАТЧА... %.0f%%",
        "steam.status.unpacking": "РОЗПАКУВАННЯ ПАТЧА...",
        "steam.status.assetsReady": "РЕСУРСИ ГОТОВІ",
        "steam.status.error": "ПОМИЛКА: %@",
        "patch.status.idle": "ОЧІКУВАННЯ ДІЇ",
        "patch.status.cleaning": "ОЧИЩЕННЯ КОНФЛІКТНИХ ФАЙЛІВ...",
        "patch.status.downloading": "ЗАВАНТАЖЕННЯ ПАТЧА... %.0f%%",
        "patch.status.unpacking": "РОЗПАКУВАННЯ ПАТЧА...",
        "patch.status.completed": "ПАТЧ УСПІШНО ЗАСТОСОВАНО",
        "patch.status.error": "ПОМИЛКА: %@",
        "folder.prompt": "Виберіть папку з Windows-версією гри (що містить .big файли)",
        "settings.title": "НАЛАШТУВАННЯ ГРИ",
        "settings.windowedEdgeScroll": "Автоскрол у віконному режимі",
        "settings.windowedEdgeScrollDesc": "Захоплює курсор миші всередині вікна гри під час матчу для скролу карти.",
        "settings.language": "Мова",
        "settings.about": "Система",
        "settings.aboutButton": "Про програму",
        "settings.cameraSection": "Камера",
        "settings.interfaceSection": "Інтерфейс",
        "settings.showHotkeyLabels": "Показувати літери гарячих клавіш",
        "settings.showHotkeyLabelsDesc": "Відображає літеру гарячої клавіші на іконці команди в панелі.",
        "settings.cameraMaxHeight": "Макс. висота (Зум)",
        "settings.cameraMinHeight": "Мін. висота (Наближення)",
        "settings.cameraSpeed": "Швидкість камери",
        "settings.fpsSection": "Продуктивність",
        "settings.statsOverlay": "Показувати оверлей FPS та Ping",
        "settings.limitFps": "Обмежити частоту кадрів",
        "settings.networkSection": "Мережа та логи",
        "settings.altEndpoint": "Альтернативний сервер",
        "settings.verboseLogging": "Детальне логування движка",
        "settings.shareLogs": "Надіслати логи",
        "settings.shareLogsHint": "Відкриє чат Telegram і ZIP — перетягни його в чат",
        "settings.shareLogsNone": "Логи ще не знайдено. Увімкніть «Детальне логування движка», запустіть гру один раз і повторіть.",
        "settings.shareLogsFailed": "Не вдалося запакувати логи. Спробуйте ще раз.",
        "settings.gameLanguage": "Мова гри",
        "settings.gameLanguageRestart": "Потрібен перезапуск гри",
        "settings.scope.global": "ГЛОБАЛЬНО",
        "settings.scope.online": "ОНЛАЙН",
        "settings.scope.lobbyHost": "ХОСТ ЛОББІ",
        "settings.scope.globalDesc": "ГЛОБАЛЬНО: Застосовується до всіх ігрових режимів (Кампанія, Сутичка, Онлайн).",
        "settings.scope.onlineDesc": "ОНЛАЙН: Працює тільки в мережевих режимах гри.",
        "settings.scope.lobbyHostDesc": "ХОСТ ЛОББІ: Застосовується тільки при створенні мережевої гри (хостингу лобі).",
        "settings.legendSection": "ЛЕГЕНДА",
        "about.windowTitle": "Про Generals Online",
        "about.nativePort": "Нативний порт для macOS",
        "about.portAuthor": "Порт для macOS: Діма Ок (OKJI)",
        "about.builtOnTop": "Розроблено на базі відкритого вихідного коду EA GPLv3",
        "about.website": "Сайт",
        "about.legal": "C&C: Generals Zero Hour™ є товарним знаком Electronic Arts.\nВихідний код ігрового движка ліцензовано під GPLv3.",
        "mod.section": "МОДИ",
        "mod.install": "ВСТАНОВИТИ",
        "mod.repair": "ВІДНОВИТИ",
        "mod.installed": "%@ встановлено",
        "mod.reinstall": "Перевстановити",
        "mod.remove": "Видалити",
        "mod.installingTitle": "ВСТАНОВЛЕННЯ %@ — ЗАЧЕКАЙТЕ",
        "mod.installingHint": "З іграми все гаразд — запуск і патч заблоковані, щоб не перервати завантаження",
        "mod.damaged": "Бракує файлів: %d — перевстановіть для відновлення",
        "mod.sizeInfo": "завантаження %@ · диск %@",
        "mod.sizeParts": " · частин: %d",
        "mod.status.notInstalled": "Не встановлено",
        "mod.status.downloading": "Завантаження — %d%%",
        "mod.status.downloadingPart": "Завантаження частини %d з %d — %d%%",
        "mod.status.unpacking": "Розпакування",
        "mod.status.unpackingPart": "Розпакування частини %d з %d",
        "mod.status.installed": "Встановлено",
        "mod.status.error": "Помилка: %@",
        "alert.folderNotSelected": "Папку з грою ще не вибрано.",
        "alert.binaryNotFound": "Виконуваний файл %@ не знайдено: %@",
        "alert.modFolderMissing": "Папка мода недоступна.",
        "alert.modConfigMissing": "У %@ відсутній %@.",
        "alert.launchFailed": "Не вдалося запустити гру: %@",
        "sidebar.reset": "СКИДАННЯ",
        "about.version": "Версія %@",
        "mod.confirmReinstallTitle": "Перевстановити %@?",
        "mod.confirmReinstallMsg": "Встановлені файли спочатку буде видалено та завантажено знову (%@).",
        "mod.confirmRemoveTitle": "Видалити %@?",
        "mod.confirmRemoveMsg": "Усі встановлені файли цього мода буде видалено.",
        "alert.cancel": "Скасувати",
        "mod.status.removing": "Видалення",
        "mod.removingTitle": "ВИДАЛЕННЯ %@ — ЗАЧЕКАЙТЕ",
        "steam.storedPasswordHint": "Натисніть, щоб підставити пароль зі сховища ключів",
        "steam.usernamePlaceholder": "Логін Steam",
        "steam.passwordPlaceholder": "Введіть пароль...",
        "steam.storedPasswordTitle": "Знайдено збережений пароль",
        "steam.storedPasswordMsg": "Для «%@» у сховищі ключів є пароль. Підставити його чи ввести новий?",
        "steam.storedPasswordUse": "Підставити",
        "steam.storedPasswordType": "Ввести вручну"
    ]

    static let hi: [String: String] = [
        "app.title": "GENERALS ONLINE",
        "app.subtitle": "कम्युनिटी MAC पोर्ट",
        "tab.steam": "STEAM (अनुशंसित)",
        "tab.local": "लोकल आर्काइव",
        "steam.credentials": "STEAM क्रेडेंशियल",
        "steam.submit": "सबमिट",
        "steam.cancel": "रद्द करें",
        "steam.download": "एसेट्स डाउनलोड करें",
        "local.path": "गेम डेटा पथ:",
        "local.locate": "चुनें",
        "local.selectHint": "दोनों गेम संस्करणों वाली मूल डायरेक्टरी चुनें",
        "local.invalidTarget": "अमान्य लक्ष्य — सब-डायरेक्टरी में ini.big / inizh.big नहीं मिला",
        "action.launch": "लॉन्च",
        "action.patch": "पैच",
        "action.init": "शुरू हो रहा है...",
        "alert.launchError": "लॉन्च त्रुटि",
        "alert.ok": "OK",
        "alert.gameNotFound": "गेम नहीं मिला",
        "alert.gameNotFoundMsg": "अकाउंट \"%@\" के पास Command & Conquer™ Generals — Zero Hour नहीं है।\n\nSteam पर गेम खरीदें, फिर \"एसेट्स डाउनलोड करें\" दोबारा दबाएं।",
        "alert.openSteamStore": "Steam स्टोर खोलें",
        "alert.close": "बंद करें",
        "alert.patchTitle": "Community Patch लागू करें?",
        "alert.patchMsg": "आपकी गेम फ़ाइलें अपरिवर्तनीय रूप से संशोधित या हटाई जा सकती हैं।\nऑनलाइन खेलने के लिए यह आवश्यक है।",
        "alert.patchButton": "पैच",
        "update.available": "अपडेट उपलब्ध: v%@",
        "update.download": "अपडेट डाउनलोड करें",
        "update.details": "विवरण देखें",
        "footer.author": "पोर्ट: OKJI (Okladnoj)",
        "steam.status.ready": "तैयार",
        "steam.status.installingSteamCMD": "STEAMCMD इंस्टॉल हो रहा है...",
        "steam.status.awaitingCreds": "क्रेडेंशियल की प्रतीक्षा",
        "steam.status.authenticating": "प्रमाणीकरण...",
        "steam.status.steamGuard": "STEAM GUARD कोड आवश्यक",
        "steam.status.downloading": "एसेट्स डाउनलोड हो रहे हैं... %@",
        "steam.status.validating": "फ़ाइलें सत्यापित हो रही हैं...",
        "steam.status.downloadingPatch": "पैच डाउनलोड हो रहा है... %.0f%%",
        "steam.status.unpacking": "पैच अनपैक हो रहा है...",
        "steam.status.assetsReady": "एसेट्स तैयार",
        "steam.status.error": "त्रुटि: %@",
        "patch.status.idle": "कार्रवाई की प्रतीक्षा",
        "patch.status.cleaning": "विरोधी फ़ाइलें हटाई जा रही हैं...",
        "patch.status.downloading": "पैच डाउनलोड हो रहा है... %.0f%%",
        "patch.status.unpacking": "पैच अनपैक हो रहा है...",
        "patch.status.completed": "पैच सफलतापूर्वक लागू",
        "patch.status.error": "त्रुटि: %@",
        "folder.prompt": "Windows गेम फ़ोल्डर चुनें (.big फ़ाइलें वाला)",
        "settings.title": "GAME SETTINGS",
        "settings.windowedEdgeScroll": "Edge Scroll in Windowed Mode",
        "settings.windowedEdgeScrollDesc": "Captures mouse cursor inside the game window during gameplay for edge scrolling.",
        "settings.language": "भाषा (Language)",
        "settings.about": "सिस्टम (System)",
        "settings.aboutButton": "Generals Online के बारे में",
        "settings.cameraSection": "कैमरा (Camera)",
        "settings.interfaceSection": "इंटरफ़ेस (Interface)",
        "settings.showHotkeyLabels": "हॉटकी अक्षर दिखाएं",
        "settings.showHotkeyLabelsDesc": "कमांड बार के आइकन पर प्रत्येक कमांड की हॉटकी का अक्षर दिखाता है।",
        "settings.cameraMaxHeight": "अधिकतम ऊंचाई (Zoom)",
        "settings.cameraMinHeight": "न्यूनतम ऊंचाई (Close)",
        "settings.cameraSpeed": "कैमरा गति",
        "settings.fpsSection": "प्रदर्शन (Performance)",
        "settings.statsOverlay": "FPS और Ping ओवरले दिखाएं",
        "settings.limitFps": "फ्रेमरेट सीमित करें",
        "settings.networkSection": "नेटवर्क और लॉग्स",
        "settings.altEndpoint": "वैकल्पic एंडपॉइंट का उपयोग करें",
        "settings.verboseLogging": "इंजन का विस्तृत लॉगिंग",
        "settings.shareLogs": "लॉग साझा करें",
        "settings.shareLogsHint": "Telegram चैट और ZIP खोलता है — इसे चैट में खींचें",
        "settings.shareLogsNone": "अभी तक कोई लॉग फ़ाइल नहीं मिली। विस्तृत इंजन लॉगिंग सक्षम करें, गेम एक बार चलाएं, फिर पुनः प्रयास करें।",
        "settings.shareLogsFailed": "लॉग को पैकेज नहीं किया जा सका। कृपया पुनः प्रयास करें।",
        "settings.gameLanguage": "गेम भाषा",
        "settings.gameLanguageRestart": "गेम पुनः प्रारंभ करना आवश्यक",
        "settings.scope.global": "वैश्विक",
        "settings.scope.online": "ऑनलाइन",
        "settings.scope.lobbyHost": "लॉबी होस्ट",
        "settings.scope.globalDesc": "वैश्विक: सभी गेम मोड (एकल खिलाड़ी, झड़प, और ऑनलाइन) पर लागू होता है।",
        "settings.scope.onlineDesc": "ऑनलाइन: केवल मल्टीप्लेयर नेटवर्क मोड में काम करता है।",
        "settings.scope.lobbyHostDesc": "लॉबी होस्ट: केवल तब लागू होता है जब आप मल्टीप्लेयर लॉबी की मेजबानी कर रहे हों।",
        "settings.legendSection": "संकेत",
        "about.windowTitle": "Generals Online के बारे में",
        "about.nativePort": "macOS नेटिव पोर्ट",
        "about.portAuthor": "Dima Ok (OKJI) द्वारा macOS पोर्ट",
        "about.builtOnTop": "EA GPLv3 ओपन-सोर्स रिलीज़ के आधार पर निर्मित",
        "about.website": "वेबसाइट",
        "about.legal": "C&C: Generals Zero Hour™ Electronic Arts का एक ट्रेडमार्क है।\nगेम इंजन सोर्स कोड GPLv3 के तहत लाइसेंस प्राप्त है।",
        "mod.section": "मॉड्स",
        "mod.install": "इंस्टॉल करें",
        "mod.repair": "मरम्मत करें",
        "mod.installed": "%@ इंस्टॉल हो गया",
        "mod.reinstall": "फिर से इंस्टॉल करें",
        "mod.remove": "हटाएं",
        "mod.installingTitle": "%@ इंस्टॉल हो रहा है — कृपया प्रतीक्षा करें",
        "mod.installingHint": "आपके गेम ठीक हैं — डाउनलोड बाधित न हो इसलिए लॉन्च और पैच बंद हैं",
        "mod.damaged": "%d फ़ाइल(ें) गायब — मरम्मत के लिए फिर से इंस्टॉल करें",
        "mod.sizeInfo": "डाउनलोड %@ · डिस्क %@",
        "mod.sizeParts": " · %d भाग",
        "mod.status.notInstalled": "इंस्टॉल नहीं है",
        "mod.status.downloading": "डाउनलोड हो रहा है — %d%%",
        "mod.status.downloadingPart": "भाग %d/%d डाउनलोड हो रहा है — %d%%",
        "mod.status.unpacking": "अनपैक हो रहा है",
        "mod.status.unpackingPart": "भाग %d/%d अनपैक हो रहा है",
        "mod.status.installed": "इंस्टॉल है",
        "mod.status.error": "त्रुटि: %@",
        "alert.folderNotSelected": "गेम फ़ोल्डर अभी तक चुना नहीं गया।",
        "alert.binaryNotFound": "%@ की executable फ़ाइल %@ पर नहीं मिली",
        "alert.modFolderMissing": "मॉड फ़ोल्डर उपलब्ध नहीं है।",
        "alert.modConfigMissing": "%@ में %@ नहीं है।",
        "alert.launchFailed": "गेम लॉन्च नहीं हो सका: %@",
        "sidebar.reset": "रीसेट",
        "about.version": "संस्करण %@",
        "mod.confirmReinstallTitle": "%@ फिर से इंस्टॉल करें?",
        "mod.confirmReinstallMsg": "इंस्टॉल फ़ाइलें पहले हटाई जाएंगी और फिर से डाउनलोड होंगी (%@)।",
        "mod.confirmRemoveTitle": "%@ हटाएं?",
        "mod.confirmRemoveMsg": "इस मॉड की सभी इंस्टॉल फ़ाइलें हटा दी जाएंगी।",
        "alert.cancel": "रद्द करें",
        "mod.status.removing": "हटाया जा रहा है",
        "mod.removingTitle": "%@ हटाया जा रहा है — कृपया प्रतीक्षा करें",
        "steam.storedPasswordHint": "कीचेन में सहेजा गया पासवर्ड भरने के लिए क्लिक करें",
        "steam.usernamePlaceholder": "Steam लॉगिन",
        "steam.passwordPlaceholder": "पासवर्ड दर्ज करें...",
        "steam.storedPasswordTitle": "सहेजा गया पासवर्ड मिला",
        "steam.storedPasswordMsg": "कीचेन में “%@” के लिए पासवर्ड सहेजा है। उसे भरें या नया दर्ज करें?",
        "steam.storedPasswordUse": "सहेजा हुआ भरें",
        "steam.storedPasswordType": "खुद दर्ज करें"
    ]

    static let zh: [String: String] = [
        "app.title": "GENERALS ONLINE",
        "app.subtitle": "社区 MAC 移植版",
        "tab.steam": "STEAM（推荐）",
        "tab.local": "本地存档",
        "steam.credentials": "STEAM 凭据",
        "steam.submit": "提交",
        "steam.cancel": "取消",
        "steam.download": "下载资源",
        "local.path": "游戏数据路径：",
        "local.locate": "选择",
        "local.selectHint": "选择包含两个游戏版本的父目录",
        "local.invalidTarget": "无效目标 — 子目录中未检测到 ini.big / inizh.big",
        "action.launch": "启动",
        "action.patch": "修补",
        "action.init": "初始化中...",
        "alert.launchError": "启动错误",
        "alert.ok": "确定",
        "alert.gameNotFound": "未找到游戏",
        "alert.gameNotFoundMsg": "账户 \"%@\" 未拥有 Command & Conquer™ Generals — Zero Hour。\n\n请在 Steam 购买游戏，然后再次点击\"下载资源\"。",
        "alert.openSteamStore": "打开 Steam 商店",
        "alert.close": "关闭",
        "alert.patchTitle": "应用社区补丁？",
        "alert.patchMsg": "您的游戏文件可能会被不可逆地修改或删除。\n这是在线游戏所必需的。",
        "alert.patchButton": "修补",
        "update.available": "可用更新：v%@",
        "update.download": "下载更新",
        "update.details": "查看详情",
        "footer.author": "移植：OKJI (Okladnoj)",
        "steam.status.ready": "就绪",
        "steam.status.installingSteamCMD": "正在安装 STEAMCMD...",
        "steam.status.awaitingCreds": "等待凭据",
        "steam.status.authenticating": "认证中...",
        "steam.status.steamGuard": "需要 STEAM GUARD 代码",
        "steam.status.downloading": "正在下载资源... %@",
        "steam.status.validating": "正在验证文件...",
        "steam.status.downloadingPatch": "正在下载补丁... %.0f%%",
        "steam.status.unpacking": "正在解压补丁...",
        "steam.status.assetsReady": "资源就绪",
        "steam.status.error": "错误：%@",
        "patch.status.idle": "等待操作",
        "patch.status.cleaning": "正在清理冲突文件...",
        "patch.status.downloading": "正在下载补丁... %.0f%%",
        "patch.status.unpacking": "正在解压补丁...",
        "patch.status.completed": "补丁应用成功",
        "patch.status.error": "错误：%@",
        "folder.prompt": "选择 Windows 游戏文件夹（包含 .big 文件）",
        "settings.title": "游戏设置",
        "settings.windowedEdgeScroll": "窗口模式边缘滚动",
        "settings.windowedEdgeScrollDesc": "在游戏过程中将鼠标限制在窗口内，以启用边缘滚动功能。",
        "settings.language": "语言 (Language)",
        "settings.about": "系统",
        "settings.aboutButton": "关于 Generals Online",
        "settings.cameraSection": "相机",
        "settings.interfaceSection": "界面",
        "settings.showHotkeyLabels": "显示快捷键字母",
        "settings.showHotkeyLabelsDesc": "在指令栏图标上显示每个指令的快捷键字母。",
        "settings.cameraMaxHeight": "最大高度 (缩放)",
        "settings.cameraMinHeight": "最小高度 (靠近)",
        "settings.cameraSpeed": "相机速度",
        "settings.fpsSection": "性能",
        "settings.statsOverlay": "显示 FPS 和 Ping 悬浮窗",
        "settings.limitFps": "限制帧率",
        "settings.networkSection": "网络与日志",
        "settings.altEndpoint": "使用备用网络端点",
        "settings.verboseLogging": "启用详细引擎日志",
        "settings.shareLogs": "分享日志",
        "settings.shareLogsHint": "打开 Telegram 聊天和 ZIP 文件 — 将其拖入聊天",
        "settings.shareLogsNone": "尚未找到日志文件。请启用详细引擎日志，运行一次游戏，然后重试。",
        "settings.shareLogsFailed": "无法打包日志。请重试。",
        "settings.gameLanguage": "游戏语言",
        "settings.gameLanguageRestart": "需要重启游戏",
        "settings.scope.global": "全局",
        "settings.scope.online": "在线",
        "settings.scope.lobbyHost": "房主",
        "settings.scope.globalDesc": "全局：适用于所有游戏模式（单人、遭遇战和在线）。",
        "settings.scope.onlineDesc": "在线：仅在多人网络模式下有效。",
        "settings.scope.lobbyHostDesc": "房主：仅在您主持（创建）多人游戏大厅时适用。",
        "settings.legendSection": "图例",
        "about.windowTitle": "关于 Generals Online",
        "about.nativePort": "macOS 原生移植版",
        "about.portAuthor": "macOS 移植者：Dima Ok (OKJI)",
        "about.builtOnTop": "基于 EA GPLv3 开源版本开发",
        "about.website": "官方网站",
        "about.legal": "C&C: Generals Zero Hour™ 是 Electronic Arts 的商标。\n游戏引擎源码基于 GPLv3 授权。",
        "mod.section": "模组",
        "mod.install": "安装",
        "mod.repair": "修复",
        "mod.installed": "%@ 已安装",
        "mod.reinstall": "重新安装",
        "mod.remove": "移除",
        "mod.installingTitle": "正在安装 %@ — 请稍候",
        "mod.installingHint": "你的游戏没有问题 — 启动和修补已锁定，以免中断下载",
        "mod.damaged": "缺少 %d 个文件 — 重新安装以修复",
        "mod.sizeInfo": "下载 %@ · 占用 %@",
        "mod.sizeParts": " · %d 个分卷",
        "mod.status.notInstalled": "未安装",
        "mod.status.downloading": "下载中 — %d%%",
        "mod.status.downloadingPart": "正在下载第 %d/%d 个分卷 — %d%%",
        "mod.status.unpacking": "解压中",
        "mod.status.unpackingPart": "正在解压第 %d/%d 个分卷",
        "mod.status.installed": "已安装",
        "mod.status.error": "错误：%@",
        "alert.folderNotSelected": "尚未选择游戏文件夹。",
        "alert.binaryNotFound": "未在 %@ 找到 %@ 的可执行文件",
        "alert.modFolderMissing": "模组文件夹不可用。",
        "alert.modConfigMissing": "%@ 缺少 %@。",
        "alert.launchFailed": "启动游戏失败：%@",
        "sidebar.reset": "重置",
        "about.version": "版本 %@",
        "mod.confirmReinstallTitle": "重新安装 %@？",
        "mod.confirmReinstallMsg": "已安装的文件将先被删除，然后重新下载（%@）。",
        "mod.confirmRemoveTitle": "移除 %@？",
        "mod.confirmRemoveMsg": "该模组已安装的所有文件都将被删除。",
        "alert.cancel": "取消",
        "mod.status.removing": "正在移除",
        "mod.removingTitle": "正在移除 %@ — 请稍候",
        "steam.storedPasswordHint": "点击以填入钥匙串中保存的密码",
        "steam.usernamePlaceholder": "Steam 账号",
        "steam.passwordPlaceholder": "请输入密码...",
        "steam.storedPasswordTitle": "找到已保存的密码",
        "steam.storedPasswordMsg": "钥匙串中保存了“%@”的密码。要使用它还是输入新密码？",
        "steam.storedPasswordUse": "使用已保存",
        "steam.storedPasswordType": "手动输入"
    ]

    static let ar: [String: String] = [
        "app.title": "GENERALS ONLINE",
        "app.subtitle": "نسخة MAC من المجتمع",
        "tab.steam": "STEAM (موصى به)",
        "tab.local": "أرشيف محلي",
        "steam.credentials": "بيانات STEAM",
        "steam.submit": "إرسال",
        "steam.cancel": "إلغاء",
        "steam.download": "تحميل الموارد",
        "local.path": "مسار بيانات اللعبة:",
        "local.locate": "تحديد",
        "local.selectHint": "حدد المجلد الرئيسي الذي يحتوي على نسختي اللعبة",
        "local.invalidTarget": "هدف غير صالح — لم يتم العثور على ini.big / inizh.big في المجلدات الفرعية",
        "action.launch": "تشغيل",
        "action.patch": "تصحيح",
        "action.init": "جارٍ التهيئة...",
        "alert.launchError": "خطأ في التشغيل",
        "alert.ok": "موافق",
        "alert.gameNotFound": "اللعبة غير موجودة",
        "alert.gameNotFoundMsg": "الحساب \"%@\" لا يملك Command & Conquer™ Generals — Zero Hour.\n\nقم بشراء اللعبة على Steam، ثم اضغط \"تحميل الموارد\" مرة أخرى.",
        "alert.openSteamStore": "فتح متجر Steam",
        "alert.close": "إغلاق",
        "alert.patchTitle": "تطبيق تصحيح المجتمع؟",
        "alert.patchMsg": "قد يتم تعديل ملفات اللعبة أو حذفها بشكل لا رجعة فيه.\nهذا مطلوب للعب عبر الإنترنت.",
        "alert.patchButton": "تصحيح",
        "update.available": "تحديث متاح: v%@",
        "update.download": "تحميل التحديث",
        "update.details": "عرض التفاصيل",
        "footer.author": "نقل: OKJI (Okladnoj)",
        "steam.status.ready": "جاهز",
        "steam.status.installingSteamCMD": "جارٍ تثبيت STEAMCMD...",
        "steam.status.awaitingCreds": "في انتظار البيانات",
        "steam.status.authenticating": "جارٍ المصادقة...",
        "steam.status.steamGuard": "مطلوب رمز STEAM GUARD",
        "steam.status.downloading": "جارٍ تحميل الموارد... %@",
        "steam.status.validating": "جارٍ التحقق من الملفات...",
        "steam.status.downloadingPatch": "جارٍ تحميل التصحيح... %.0f%%",
        "steam.status.unpacking": "جارٍ فك التصحيح...",
        "steam.status.assetsReady": "الموارد جاهزة",
        "steam.status.error": "خطأ: %@",
        "patch.status.idle": "في انتظار الإجراء",
        "patch.status.cleaning": "جارٍ تنظيف الملفات المتعارضة...",
        "patch.status.downloading": "جارٍ تحميل التصحيح... %.0f%%",
        "patch.status.unpacking": "جارٍ فك التصحيح...",
        "patch.status.completed": "تم تطبيق التصحيح بنجاح",
        "patch.status.error": "خطأ: %@",
        "folder.prompt": "حدد مجلد لعبة Windows (يحتوي على ملفات .big)",
        "settings.title": "GAME SETTINGS",
        "settings.windowedEdgeScroll": "Edge Scroll in Windowed Mode",
        "settings.windowedEdgeScrollDesc": "Captures mouse cursor inside the game window during gameplay for edge scrolling.",
        "settings.language": "اللغة (Language)",
        "settings.about": "النظام (System)",
        "settings.aboutButton": "حول Generals Online",
        "settings.cameraSection": "الكاميرا",
        "settings.interfaceSection": "الواجهة",
        "settings.showHotkeyLabels": "إظهار أحرف مفاتيح الاختصار",
        "settings.showHotkeyLabelsDesc": "يعرض حرف مفتاح الاختصار لكل أمر على أيقونته في شريط الأوامر.",
        "settings.cameraMaxHeight": "الارتفاع الأقصى (التقريب)",
        "settings.cameraMinHeight": "الارتفاع الأدنى (التبعيد)",
        "settings.cameraSpeed": "سرعة الكاميرا",
        "settings.fpsSection": "الأداء",
        "settings.statsOverlay": "عرض إحصائيات FPS و Ping",
        "settings.limitFps": "تحديد معدل الإطارات",
        "settings.networkSection": "الشبكة والسجلات",
        "settings.altEndpoint": "استخدام خادم بديل",
        "settings.verboseLogging": "تسجيل تفصيلي للمحرك",
        "settings.shareLogs": "مشاركة السجلات",
        "settings.shareLogsHint": "يفتح محادثة Telegram وملف ZIP — اسحبه إلى المحادثة",
        "settings.shareLogsNone": "لم يتم العثور على ملفات سجل بعد. فعّل تسجيل المحرك التفصيلي، شغّل اللعبة مرة واحدة، ثم أعد المحاولة.",
        "settings.shareLogsFailed": "تعذّر حزم السجلات. يرجى المحاولة مرة أخرى.",
        "settings.gameLanguage": "لغة اللعبة",
        "settings.gameLanguageRestart": "يتطلب إعادة تشغيل اللعبة",
        "settings.scope.global": "GLOBAL",
        "settings.scope.online": "ONLINE",
        "settings.scope.lobbyHost": "LOBBY HOST",
        "settings.scope.globalDesc": "GLOBAL: Applies to all game modes (Singleplayer, Skirmish, and Online).",
        "settings.scope.onlineDesc": "ONLINE: Only works in multiplayer network modes.",
        "settings.scope.lobbyHostDesc": "LOBBY HOST: Only applies when hosting multiplayer lobbies.",
        "settings.legendSection": "دليل الرموز",
        "about.windowTitle": "حول Generals Online",
        "about.nativePort": "نسخة macOS الأصلية",
        "about.portAuthor": "نقل إلى macOS بواسطة Dima Ok (OKJI)",
        "about.builtOnTop": "مبني على إصدار EA GPLv3 مفتوح المصدر",
        "about.website": "الموقع الإلكتروني",
        "about.legal": "C&C: Generals Zero Hour™ هي علامة تجارية لشركة Electronic Arts.\nرمز مصدر محرك اللعبة مرخص بموجب GPLv3.",
        "mod.section": "التعديلات",
        "mod.install": "تثبيت",
        "mod.repair": "إصلاح",
        "mod.installed": "تم تثبيت %@",
        "mod.reinstall": "إعادة التثبيت",
        "mod.remove": "إزالة",
        "mod.installingTitle": "جارٍ تثبيت %@ — يرجى الانتظار",
        "mod.installingHint": "ألعابك بخير — التشغيل والتصحيح مقفلان حتى لا ينقطع التحميل",
        "mod.damaged": "%d ملف مفقود — أعد التثبيت للإصلاح",
        "mod.sizeInfo": "التحميل %@ · القرص %@",
        "mod.sizeParts": " · %d أجزاء",
        "mod.status.notInstalled": "غير مثبت",
        "mod.status.downloading": "جارٍ التحميل — %d%%",
        "mod.status.downloadingPart": "جارٍ تحميل الجزء %d من %d — %d%%",
        "mod.status.unpacking": "جارٍ فك الضغط",
        "mod.status.unpackingPart": "جارٍ فك ضغط الجزء %d من %d",
        "mod.status.installed": "مثبت",
        "mod.status.error": "خطأ: %@",
        "alert.folderNotSelected": "لم يتم تحديد مجلد اللعبة بعد.",
        "alert.binaryNotFound": "لم يتم العثور على ملف %@ التنفيذي في %@",
        "alert.modFolderMissing": "مجلد التعديل غير متاح.",
        "alert.modConfigMissing": "%@ ينقصه %@.",
        "alert.launchFailed": "تعذّر تشغيل اللعبة: %@",
        "sidebar.reset": "إعادة تعيين",
        "about.version": "الإصدار %@",
        "mod.confirmReinstallTitle": "إعادة تثبيت %@؟",
        "mod.confirmReinstallMsg": "سيتم حذف الملفات المثبتة أولاً ثم تنزيلها من جديد (%@).",
        "mod.confirmRemoveTitle": "إزالة %@؟",
        "mod.confirmRemoveMsg": "سيتم حذف جميع الملفات المثبتة لهذا التعديل.",
        "alert.cancel": "إلغاء",
        "mod.status.removing": "جارٍ الإزالة",
        "mod.removingTitle": "جارٍ إزالة %@ — يرجى الانتظار",
        "steam.storedPasswordHint": "انقر لتعبئة كلمة المرور المحفوظة في سلسلة المفاتيح",
        "steam.usernamePlaceholder": "اسم مستخدم Steam",
        "steam.passwordPlaceholder": "أدخل كلمة المرور...",
        "steam.storedPasswordTitle": "تم العثور على كلمة مرور محفوظة",
        "steam.storedPasswordMsg": "توجد كلمة مرور لـ «%@» في سلسلة المفاتيح. هل تستخدمها أم تُدخل واحدة جديدة؟",
        "steam.storedPasswordUse": "استخدام المحفوظة",
        "steam.storedPasswordType": "إدخال يدوي"
    ]

    static let kk: [String: String] = [
        "app.title": "GENERALS ONLINE",
        "app.subtitle": "ҚАУЫМДАСТЫҚ MAC ПОРТЫ",
        "tab.steam": "STEAM (ҰСЫНЫЛАДЫ)",
        "tab.local": "ЖЕРГІЛІКТІ МҰРАҒАТ",
        "steam.credentials": "STEAM ДЕРЕКТЕРІ",
        "steam.submit": "ЖІБЕРУ",
        "steam.cancel": "БОЛДЫРМАУ",
        "steam.download": "РЕСУРСТАРДЫ ЖҮКТЕУ",
        "local.path": "ОЙЫН ДЕРЕКТЕРІНІҢ ЖОЛЫ:",
        "local.locate": "ТАҢДАУ",
        "local.selectHint": "ОЙЫННЫҢ ЕКІ НҰСҚАСЫ БАР АТА-АНА ҚАЛТАСЫН КӨРСЕТІҢІЗ",
        "local.invalidTarget": "ЖАРАМСЫЗ МАҚСАТ — ішкі қалталарда ini.big / inizh.big табылмады",
        "action.launch": "ІСКЕ ҚОСУ",
        "action.patch": "ПАТЧ",
        "action.init": "ИНИЦИАЛИЗАЦИЯ...",
        "alert.launchError": "Іске қосу қатесі",
        "alert.ok": "OK",
        "alert.gameNotFound": "Ойын табылмады",
        "alert.gameNotFoundMsg": "«%@» тіркелгісінде Command & Conquer™ Generals — Zero Hour жоқ.\n\nSteam-де ойынды сатып алыңыз, содан кейін «Ресурстарды жүктеу» түймесін қайта басыңыз.",
        "alert.openSteamStore": "Steam дүкенін ашу",
        "alert.close": "Жабу",
        "alert.patchTitle": "Community Patch қолдану керек пе?",
        "alert.patchMsg": "Ойын файлдарыңыз қайтарылмайтын түрде өзгертілуі немесе жойылуы мүмкін.\nБұл онлайн ойнау үшін қажет.",
        "alert.patchButton": "Патч",
        "update.available": "ЖАҢАРТУ ҚОЛЖЕТІМДІ: v%@",
        "update.download": "ЖАҢАРТУДЫ ЖҮКТЕУ",
        "update.details": "ТОЛЫҒЫРАҚ",
        "footer.author": "Порт: OKJI (Okladnoj)",
        "steam.status.ready": "ДАЙЫН",
        "steam.status.installingSteamCMD": "STEAMCMD ОРНАТЫЛУДА...",
        "steam.status.awaitingCreds": "ДЕРЕКТЕРДІ КҮТУ",
        "steam.status.authenticating": "АУТЕНТИФИКАЦИЯ...",
        "steam.status.steamGuard": "STEAM GUARD КОДЫ ҚАЖЕТ",
        "steam.status.downloading": "РЕСУРСТАР ЖҮКТЕЛУДЕ... %@",
        "steam.status.validating": "ФАЙЛДАР ТЕКСЕРІЛУДЕ...",
        "steam.status.downloadingPatch": "ПАТЧ ЖҮКТЕЛУДЕ... %.0f%%",
        "steam.status.unpacking": "ПАТЧ АШЫЛУДА...",
        "steam.status.assetsReady": "РЕСУРСТАР ДАЙЫН",
        "steam.status.error": "ҚАТЕ: %@",
        "patch.status.idle": "ӘРЕКЕТТІ КҮТУ",
        "patch.status.cleaning": "ҚАЙШЫЛЫҚТЫ ФАЙЛДАР ТАЗАЛАНУДА...",
        "patch.status.downloading": "ПАТЧ ЖҮКТЕЛУДЕ... %.0f%%",
        "patch.status.unpacking": "ПАТЧ АШЫЛУДА...",
        "patch.status.completed": "ПАТЧ СӘТТІ ҚОЛДАНЫЛДЫ",
        "patch.status.error": "ҚАТЕ: %@",
        "folder.prompt": "Windows ойын қалтасын таңдаңыз (.big файлдары бар)",
        "settings.title": "ОЙЫН БАПТАУЛАРЫ",
        "settings.windowedEdgeScroll": "Терезе режиміндегі автоскролл",
        "settings.windowedEdgeScrollDesc": "Картаны скроллдау үшін тінтуір меңзерін ойын терезесінің ішінде шектейді.",
        "settings.language": "Тіл (Language)",
        "settings.about": "Жүйе (System)",
        "settings.aboutButton": "Generals Online туралы",
        "settings.cameraSection": "Камера",
        "settings.interfaceSection": "Интерфейс",
        "settings.showHotkeyLabels": "Жылдам пернелер әріптерін көрсету",
        "settings.showHotkeyLabelsDesc": "Командалар тақтасындағы белгішеде команданың жылдам перне әрпін көрсетеді.",
        "settings.cameraMaxHeight": "Максималды биіктік (Зум)",
        "settings.cameraMinHeight": "Минималды биіктік (Жақындату)",
        "settings.cameraSpeed": "Камера жылдамдығы",
        "settings.fpsSection": "Өнімділік",
        "settings.statsOverlay": "FPS пен Ping оверлейін көрсету",
        "settings.limitFps": "Кадр жиілігін шектеу",
        "settings.networkSection": "Желі және журналдар",
        "settings.altEndpoint": "Баламалы серверді қолдану",
        "settings.verboseLogging": "Қозғалтқыштың толық журналы",
        "settings.shareLogs": "Журналдарды бөлісу",
        "settings.shareLogsHint": "Telegram чатын және ZIP файлын ашады — оны чатқа сүйреп апарыңыз",
        "settings.shareLogsNone": "Журнал файлдары әлі жоқ. Толық журналдауды қосып, ойынды бір рет іске қосыңыз да, қайталап көріңіз.",
        "settings.shareLogsFailed": "Журналдарды буу мүмкін болмады. Қайталап көріңіз.",
        "settings.gameLanguage": "Ойын тілі",
        "settings.gameLanguageRestart": "Ойынды қайта іске қосу қажет",
        "settings.scope.global": "ЖАЛПЫ",
        "settings.scope.online": "ОНЛАЙН",
        "settings.scope.lobbyHost": "ЛОББИ ХОСТЫ",
        "settings.scope.globalDesc": "ЖАЛПЫ: Барлық ойын режимдеріне қолданылады (науқан, шайқас, онлайн).",
        "settings.scope.onlineDesc": "ОНЛАЙН: Тек желілік ойын режимдерінде жұмыс істейді.",
        "settings.scope.lobbyHostDesc": "ЛОББИ ХОСТЫ: Тек желілік ойын бөлмесін (лобби) жасаған кезде ғана қолданылады.",
        "settings.legendSection": "ТҮСІНДІРМЕ",
        "about.windowTitle": "Generals Online туралы",
        "about.nativePort": "macOS нативті порты",
        "about.portAuthor": "macOS порты: Дима Ок (OKJI)",
        "about.builtOnTop": "EA GPLv3 ашық бастапқы коды негізінде жасалған",
        "about.website": "Веб-сайт",
        "about.legal": "C&C: Generals Zero Hour™ — Electronic Arts сауда белгісі.\nОйын қозғалтқышының бастапқы коды GPLv3 лицензиясымен таратылады.",
        "mod.section": "МОДТАР",
        "mod.install": "ОРНАТУ",
        "mod.repair": "ҚАЛПЫНА КЕЛТІРУ",
        "mod.installed": "%@ орнатылды",
        "mod.reinstall": "Қайта орнату",
        "mod.remove": "Жою",
        "mod.installingTitle": "%@ ОРНАТЫЛУДА — КҮТЕ ТҰРЫҢЫЗ",
        "mod.installingHint": "Ойындарыңыз аман — жүктеу үзілмес үшін іске қосу мен патч бұғатталған",
        "mod.damaged": "%d файл жетіспейді — қалпына келтіру үшін қайта орнатыңыз",
        "mod.sizeInfo": "жүктеу %@ · диск %@",
        "mod.sizeParts": " · %d бөлік",
        "mod.status.notInstalled": "Орнатылмаған",
        "mod.status.downloading": "Жүктелуде — %d%%",
        "mod.status.downloadingPart": "%d/%d бөлігі жүктелуде — %d%%",
        "mod.status.unpacking": "Ашылуда",
        "mod.status.unpackingPart": "%d/%d бөлігі ашылуда",
        "mod.status.installed": "Орнатылды",
        "mod.status.error": "Қате: %@",
        "alert.folderNotSelected": "Ойын қалтасы әлі таңдалмаған.",
        "alert.binaryNotFound": "%@ орындалатын файлы табылмады: %@",
        "alert.modFolderMissing": "Мод қалтасы қолжетімсіз.",
        "alert.modConfigMissing": "%@ ішінде %@ жоқ.",
        "alert.launchFailed": "Ойынды іске қосу мүмкін болмады: %@",
        "sidebar.reset": "ЫСЫРУ",
        "about.version": "Нұсқа %@",
        "mod.confirmReinstallTitle": "%@ қайта орнатылсын ба?",
        "mod.confirmReinstallMsg": "Орнатылған файлдар алдымен жойылып, қайта жүктеледі (%@).",
        "mod.confirmRemoveTitle": "%@ жойылсын ба?",
        "mod.confirmRemoveMsg": "Осы модтың барлық орнатылған файлдары жойылады.",
        "alert.cancel": "Болдырмау",
        "mod.status.removing": "Жойылуда",
        "mod.removingTitle": "%@ ЖОЙЫЛУДА — КҮТЕ ТҰРЫҢЫЗ",
        "steam.storedPasswordHint": "Кілттер тізбегінде сақталған құпия сөзді қою үшін басыңыз",
        "steam.usernamePlaceholder": "Steam логині",
        "steam.passwordPlaceholder": "Құпия сөзді енгізіңіз...",
        "steam.storedPasswordTitle": "Сақталған құпия сөз табылды",
        "steam.storedPasswordMsg": "«%@» үшін кілттер тізбегінде құпия сөз бар. Соны қою керек пе, әлде жаңасын енгізесіз бе?",
        "steam.storedPasswordUse": "Сақталғанды қою",
        "steam.storedPasswordType": "Қолмен енгізу"
    ]

    static let vi: [String: String] = [
        "app.title": "GENERALS ONLINE",
        "app.subtitle": "PHIÊN BẢN MAC CỘNG ĐỒNG",
        "tab.steam": "STEAM (KHUYẾN NGHỊ)",
        "tab.local": "LƯU TRỮ CỤC BỘ",
        "steam.credentials": "THÔNG TIN STEAM",
        "steam.submit": "GỬI",
        "steam.cancel": "HỦY",
        "steam.download": "TẢI TÀI NGUYÊN",
        "local.path": "ĐƯỜNG DẪN DỮ LIỆU TRÒ CHƠI:",
        "local.locate": "CHỌN",
        "local.selectHint": "CHỌN THƯ MỤC GỐC CHỨA CẢ HAI PHIÊN BẢN TRÒ CHƠI",
        "local.invalidTarget": "MỤC TIÊU KHÔNG HỢP LỆ — Không tìm thấy ini.big / inizh.big trong thư mục con",
        "action.launch": "CHẠY",
        "action.patch": "VÁ",
        "action.init": "ĐANG KHỞI TẠO...",
        "alert.launchError": "Lỗi khởi chạy",
        "alert.ok": "OK",
        "alert.gameNotFound": "Không tìm thấy trò chơi",
        "alert.gameNotFoundMsg": "Tài khoản \"%@\" không sở hữu Command & Conquer™ Generals — Zero Hour.\n\nMua trò chơi trên Steam, sau đó nhấn \"Tải tài nguyên\" lần nữa.",
        "alert.openSteamStore": "Mở Steam Store",
        "alert.close": "Đóng",
        "alert.patchTitle": "Áp dụng Community Patch?",
        "alert.patchMsg": "Các tệp trò chơi có thể bị sửa đổi hoặc xóa không thể khôi phục.\nĐiều này cần thiết để chơi trực tuyến.",
        "alert.patchButton": "Vá",
        "update.available": "CÓ BẢN CẬP NHẬT: v%@",
        "update.download": "TẢI BẢN CẬP NHẬT",
        "update.details": "XEM CHI TIẾT",
        "footer.author": "Chuyển đổi: OKJI (Okladnoj)",
        "steam.status.ready": "SẴN SÀNG",
        "steam.status.installingSteamCMD": "ĐANG CÀI ĐẶT STEAMCMD...",
        "steam.status.awaitingCreds": "ĐANG CHỜ THÔNG TIN",
        "steam.status.authenticating": "ĐANG XÁC THỰC...",
        "steam.status.steamGuard": "CẦN MÃ STEAM GUARD",
        "steam.status.downloading": "ĐANG TẢI TÀI NGUYÊN... %@",
        "steam.status.validating": "ĐANG KIỂM TRA TỆP...",
        "steam.status.downloadingPatch": "ĐANG TẢI BẢN VÁ... %.0f%%",
        "steam.status.unpacking": "ĐANG GIẢI NÉN BẢN VÁ...",
        "steam.status.assetsReady": "TÀI NGUYÊN SẴN SÀNG",
        "steam.status.error": "LỖI: %@",
        "patch.status.idle": "CHỜ HÀNH ĐỘNG",
        "patch.status.cleaning": "ĐANG XÓA TỆP XUNG ĐỘT...",
        "patch.status.downloading": "ĐANG TẢI BẢN VÁ... %.0f%%",
        "patch.status.unpacking": "ĐANG GIẢI NÉN BẢN VÁ...",
        "patch.status.completed": "ÁP DỤNG BẢN VÁ THÀNH CÔNG",
        "patch.status.error": "LỖI: %@",
        "folder.prompt": "Chọn thư mục trò chơi Windows (chứa tệp .big)",
        "settings.title": "GAME SETTINGS",
        "settings.windowedEdgeScroll": "Edge Scroll in Windowed Mode",
        "settings.windowedEdgeScrollDesc": "Captures mouse cursor inside the game window during gameplay for edge scrolling.",
        "settings.language": "Ngôn ngữ (Language)",
        "settings.about": "Hệ thống",
        "settings.aboutButton": "Về Generals Online",
        "settings.cameraSection": "Camera",
        "settings.interfaceSection": "Giao diện",
        "settings.showHotkeyLabels": "Hiển thị chữ phím tắt",
        "settings.showHotkeyLabelsDesc": "Hiển thị chữ phím tắt của mỗi lệnh trên biểu tượng ở thanh lệnh.",
        "settings.cameraMaxHeight": "Chiều cao tối đa (Zoom)",
        "settings.cameraMinHeight": "Chiều cao tối thiểu (Gần)",
        "settings.cameraSpeed": "Tốc độ camera",
        "settings.fpsSection": "Hiệu năng",
        "settings.statsOverlay": "Hiển thị FPS & Ping",
        "settings.limitFps": "Giới hạn khung hình",
        "settings.networkSection": "Mạng & Nhật ký",
        "settings.altEndpoint": "Sử dụng máy chủ dự phòng",
        "settings.verboseLogging": "Ghi nhật ký chi tiết",
        "settings.shareLogs": "Chia sẻ nhật ký",
        "settings.shareLogsHint": "Mở cuộc trò chuyện Telegram và tệp ZIP — kéo nó vào cuộc trò chuyện",
        "settings.shareLogsNone": "Chưa tìm thấy tệp nhật ký. Bật Ghi nhật ký chi tiết, chạy trò chơi một lần rồi thử lại.",
        "settings.shareLogsFailed": "Không thể đóng gói nhật ký. Vui lòng thử lại.",
        "settings.gameLanguage": "Ngôn ngữ trò chơi",
        "settings.gameLanguageRestart": "Cần khởi động lại trò chơi",
        "settings.scope.global": "TOÀN CỤC",
        "settings.scope.online": "TRỰC TUYẾN",
        "settings.scope.lobbyHost": "CHỦ PHÒNG",
        "settings.scope.globalDesc": "TOÀN CỤC: Áp dụng cho tất cả chế độ chơi (Chơi đơn, Trận đấu và Trực tuyến).",
        "settings.scope.onlineDesc": "TRỰC TUYẾN: Chỉ hoạt động trong chế độ chơi mạng nhiều người.",
        "settings.scope.lobbyHostDesc": "CHỦ PHÒNG: Chỉ áp dụng khi làm chủ phòng chờ nhiều người chơi.",
        "settings.legendSection": "CHÚ GIẢI",
        "about.windowTitle": "Về Generals Online",
        "about.nativePort": "Bản chuyển đổi gốc cho macOS",
        "about.portAuthor": "Bản chuyển đổi macOS bởi Dima Ok (OKJI)",
        "about.builtOnTop": "Được xây dựng trên nền tảng nguồn mở EA GPLv3",
        "about.website": "Trang web",
        "about.legal": "C&C: Generals Zero Hour™ là nhãn hiệu của Electronic Arts.\nMã nguồn công cụ trò chơi được cấp phép theo GPLv3.",
        "mod.section": "MOD",
        "mod.install": "CÀI ĐẶT",
        "mod.repair": "SỬA CHỮA",
        "mod.installed": "Đã cài %@",
        "mod.reinstall": "Cài lại",
        "mod.remove": "Gỡ bỏ",
        "mod.installingTitle": "ĐANG CÀI %@ — VUI LÒNG ĐỢI",
        "mod.installingHint": "Game của bạn vẫn ổn — khởi chạy và vá bị khoá để không làm gián đoạn tải xuống",
        "mod.damaged": "Thiếu %d tệp — cài lại để sửa",
        "mod.sizeInfo": "tải %@ · đĩa %@",
        "mod.sizeParts": " · %d phần",
        "mod.status.notInstalled": "Chưa cài đặt",
        "mod.status.downloading": "Đang tải — %d%%",
        "mod.status.downloadingPart": "Đang tải phần %d/%d — %d%%",
        "mod.status.unpacking": "Đang giải nén",
        "mod.status.unpackingPart": "Đang giải nén phần %d/%d",
        "mod.status.installed": "Đã cài đặt",
        "mod.status.error": "Lỗi: %@",
        "alert.folderNotSelected": "Chưa chọn thư mục game.",
        "alert.binaryNotFound": "Không tìm thấy tệp thực thi %@ tại %@",
        "alert.modFolderMissing": "Thư mục mod không khả dụng.",
        "alert.modConfigMissing": "%@ thiếu %@.",
        "alert.launchFailed": "Không thể khởi chạy game: %@",
        "sidebar.reset": "ĐẶT LẠI",
        "about.version": "Phiên bản %@",
        "mod.confirmReinstallTitle": "Cài lại %@?",
        "mod.confirmReinstallMsg": "Các tệp đã cài sẽ bị xoá trước rồi tải lại (%@).",
        "mod.confirmRemoveTitle": "Gỡ %@?",
        "mod.confirmRemoveMsg": "Tất cả tệp đã cài của mod này sẽ bị xoá.",
        "alert.cancel": "Huỷ",
        "mod.status.removing": "Đang gỡ",
        "mod.removingTitle": "ĐANG GỠ %@ — VUI LÒNG ĐỢI",
        "steam.storedPasswordHint": "Nhấn để điền mật khẩu đã lưu trong keychain",
        "steam.usernamePlaceholder": "Tài khoản Steam",
        "steam.passwordPlaceholder": "Nhập mật khẩu...",
        "steam.storedPasswordTitle": "Đã tìm thấy mật khẩu đã lưu",
        "steam.storedPasswordMsg": "Keychain có mật khẩu cho “%@”. Dùng mật khẩu đó hay nhập mật khẩu mới?",
        "steam.storedPasswordUse": "Dùng đã lưu",
        "steam.storedPasswordType": "Tự nhập"
    ]

    static let pl: [String: String] = [
        "app.title": "GENERALS ONLINE",
        "app.subtitle": "PORT MAC OD SPOŁECZNOŚCI",
        "tab.steam": "STEAM (ZALECANE)",
        "tab.local": "ARCHIWUM LOKALNE",
        "steam.credentials": "DANE LOGOWANIA STEAM",
        "steam.submit": "ZALOGUJ",
        "steam.cancel": "ANULUJ",
        "steam.download": "POBIERZ ZASOBY",
        "local.path": "ŚCIEŻKA DANYCH GRY:",
        "local.locate": "WYBIERZ",
        "local.selectHint": "WSKAŻ FOLDER NADRZĘDNY ZAWIERAJĄCY OBE WERSJE GRY",
        "local.invalidTarget": "NIEPRAWIDŁOWY CEL — Nie wykryto ini.big / inizh.big w podkatalogach",
        "action.launch": "URUCHOM",
        "action.patch": "ŁATKA",
        "action.init": "INICJALIZACJA...",
        "alert.launchError": "Błąd uruchamiania",
        "alert.ok": "OK",
        "alert.gameNotFound": "Nie znaleziono gry",
        "alert.gameNotFoundMsg": "Konto \"%@\" nie posiada Command & Conquer™ Generals — Zero Hour.\n\nKup grę na Steam, a następnie ponownie naciśnij \"Pobierz zasoby\".",
        "alert.openSteamStore": "Otwórz Steam Store",
        "alert.close": "Zamknij",
        "alert.patchTitle": "Zastosować Community Patch?",
        "alert.patchMsg": "Pliki gry mogą zostać nieodwracalnie zmodyfikowane lub usunięte.\nJest to wymagane do gry online.",
        "alert.patchButton": "Łatka",
        "update.available": "DOSTĘPNA AKTUALIZACJA: v%@",
        "update.download": "POBIERZ AKTUALIZACJĘ",
        "update.details": "SZCZEGÓŁY",
        "footer.author": "Port: OKJI (Okladnoj)",
        "steam.status.ready": "GOTOWE",
        "steam.status.installingSteamCMD": "INSTALOWANIE STEAMCMD...",
        "steam.status.awaitingCreds": "OCZEKIWANIE NA DANE",
        "steam.status.authenticating": "UWIERZYTELNIANIE...",
        "steam.status.steamGuard": "WYMAGANY KOD STEAM GUARD",
        "steam.status.downloading": "POBIERANIE ZASOBÓW... %@",
        "steam.status.validating": "WERYFIKACJA PLIKÓW...",
        "steam.status.downloadingPatch": "POBIERANIE ŁATKI... %.0f%%",
        "steam.status.unpacking": "ROZPAKOWYWANIE ŁATKI...",
        "steam.status.assetsReady": "ZASOBY GOTOWE",
        "steam.status.error": "BŁĄD: %@",
        "patch.status.idle": "OCZEKIWANIE NA DZIAŁANIE",
        "patch.status.cleaning": "CZYSZCZENIE PLIKÓW KONFLIKTOWYCH...",
        "patch.status.downloading": "POBIERANIE ŁATKI... %.0f%%",
        "patch.status.unpacking": "ROZPAKOWYWANIE ŁATKI...",
        "patch.status.completed": "ŁATKA ZASTOSOWANA POMYŚLNIE",
        "patch.status.error": "BŁĄD: %@",
        "folder.prompt": "Wybierz folder gry Windows (zawierający pliki .big)",
        "settings.title": "USTAWIENIA GRY",
        "settings.windowedEdgeScroll": "Przewijanie przy krawędzi w trybie okienkowym",
        "settings.windowedEdgeScrollDesc": "Ogranicza kursor myszy do okna gry, aby umożliwić przewijanie przy krawędzi.",
        "settings.language": "Język (Language)",
        "settings.about": "System",
        "settings.aboutButton": "O Generals Online",
        "settings.cameraSection": "Kamera",
        "settings.interfaceSection": "Interfejs",
        "settings.showHotkeyLabels": "Pokaż litery skrótów",
        "settings.showHotkeyLabelsDesc": "Wyświetla literę skrótu klawiszowego na ikonie polecenia na pasku.",
        "settings.cameraMaxHeight": "Maks. wysokość (Zoom)",
        "settings.cameraMinHeight": "Min. wysokość (Zbliżenie)",
        "settings.cameraSpeed": "Prędkość kamery",
        "settings.fpsSection": "Wydajność",
        "settings.statsOverlay": "Pokaż nakładkę FPS i Ping",
        "settings.limitFps": "Ogranicz liczbę klatek",
        "settings.networkSection": "Sieć i dzienniki",
        "settings.altEndpoint": "Użyj alternatywnego serwera",
        "settings.verboseLogging": "Szczegółowe logowanie silnika",
        "settings.shareLogs": "Udostępnij logi",
        "settings.shareLogsHint": "Otwiera czat Telegram i plik ZIP — przeciągnij go do czatu",
        "settings.shareLogsNone": "Nie znaleziono jeszcze plików logów. Włącz szczegółowe logowanie silnika, uruchom grę raz i spróbuj ponownie.",
        "settings.shareLogsFailed": "Nie udało się spakować logów. Spróbuj ponownie.",
        "settings.gameLanguage": "Język gry",
        "settings.gameLanguageRestart": "Wymaga restartu gry",
        "settings.scope.global": "GLOBALNE",
        "settings.scope.online": "ONLINE",
        "settings.scope.lobbyHost": "HOST LOBBY",
        "settings.scope.globalDesc": "GLOBALNE: Dotyczy wszystkich trybów gry (kampania, potyczka, online).",
        "settings.scope.onlineDesc": "ONLINE: Działa tylko w sieciowych trybach wieloosobowych.",
        "settings.scope.lobbyHostDesc": "HOST LOBBY: Dotyczy tylko sytuacji, gdy hostujesz poczekalnię wieloosobową.",
        "settings.legendSection": "LEGENDA",
        "about.windowTitle": "O Generals Online",
        "about.nativePort": "Natywny port macOS",
        "about.portAuthor": "Port macOS autorstwa Dima Ok (OKJI)",
        "about.builtOnTop": "Zbudowano na bazie wersji open-source EA GPLv3",
        "about.website": "Strona internetowa",
        "about.legal": "C&C: Generals Zero Hour™ jest znakiem towarowym Electronic Arts.\nKod źródłowy silnika gry licencjonowany na GPLv3.",
        "mod.section": "MODY",
        "mod.install": "ZAINSTALUJ",
        "mod.repair": "NAPRAW",
        "mod.installed": "%@ zainstalowany",
        "mod.reinstall": "Zainstaluj ponownie",
        "mod.remove": "Usuń",
        "mod.installingTitle": "INSTALOWANIE %@ — PROSZĘ CZEKAĆ",
        "mod.installingHint": "Twoje gry są bezpieczne — uruchamianie i łatka są zablokowane, aby nie przerwać pobierania",
        "mod.damaged": "Brakuje plików: %d — zainstaluj ponownie, aby naprawić",
        "mod.sizeInfo": "pobieranie %@ · dysk %@",
        "mod.sizeParts": " · części: %d",
        "mod.status.notInstalled": "Niezainstalowany",
        "mod.status.downloading": "Pobieranie — %d%%",
        "mod.status.downloadingPart": "Pobieranie części %d z %d — %d%%",
        "mod.status.unpacking": "Rozpakowywanie",
        "mod.status.unpackingPart": "Rozpakowywanie części %d z %d",
        "mod.status.installed": "Zainstalowany",
        "mod.status.error": "Błąd: %@",
        "alert.folderNotSelected": "Nie wybrano jeszcze folderu gry.",
        "alert.binaryNotFound": "Nie znaleziono pliku %@ w: %@",
        "alert.modFolderMissing": "Folder moda jest niedostępny.",
        "alert.modConfigMissing": "W %@ brakuje %@.",
        "alert.launchFailed": "Nie udało się uruchomić gry: %@",
        "sidebar.reset": "RESET",
        "about.version": "Wersja %@",
        "mod.confirmReinstallTitle": "Zainstalować %@ ponownie?",
        "mod.confirmReinstallMsg": "Zainstalowane pliki zostaną najpierw usunięte i pobrane ponownie (%@).",
        "mod.confirmRemoveTitle": "Usunąć %@?",
        "mod.confirmRemoveMsg": "Wszystkie zainstalowane pliki tego moda zostaną usunięte.",
        "alert.cancel": "Anuluj",
        "mod.status.removing": "Usuwanie",
        "mod.removingTitle": "USUWANIE %@ — PROSZĘ CZEKAĆ",
        "steam.storedPasswordHint": "Kliknij, aby wstawić hasło zapisane w pęku kluczy",
        "steam.usernamePlaceholder": "Login Steam",
        "steam.passwordPlaceholder": "Wpisz hasło...",
        "steam.storedPasswordTitle": "Znaleziono zapisane hasło",
        "steam.storedPasswordMsg": "W pęku kluczy jest hasło dla „%@”. Użyć go czy wpisać nowe?",
        "steam.storedPasswordUse": "Użyj zapisanego",
        "steam.storedPasswordType": "Wpisz ręcznie"
    ]

    static let de: [String: String] = [
        "app.title": "GENERALS ONLINE",
        "app.subtitle": "COMMUNITY MAC PORT",
        "tab.steam": "STEAM (EMPFOHLEN)",
        "tab.local": "LOKALES ARCHIV",
        "steam.credentials": "STEAM-ANMELDEDATEN",
        "steam.submit": "ANMELDEN",
        "steam.cancel": "ABBRECHEN",
        "steam.download": "ASSETS HERUNTERLADEN",
        "local.path": "SPIELDATEN-PFAD:",
        "local.locate": "AUSWÄHLEN",
        "local.selectHint": "WÄHLEN SIE DEN ÜBERGEORDNETEN ORDNER MIT BEIDEN SPIELVERSIONEN",
        "local.invalidTarget": "UNGÜLTIGES ZIEL — Keine ini.big / inizh.big in Unterverzeichnissen gefunden",
        "action.launch": "STARTEN",
        "action.patch": "PATCH",
        "action.init": "INITIALISIERUNG...",
        "alert.launchError": "Startfehler",
        "alert.ok": "OK",
        "alert.gameNotFound": "Spiel nicht gefunden",
        "alert.gameNotFoundMsg": "Das Konto \"%@\" besitzt Command & Conquer™ Generals — Zero Hour nicht.\n\nKaufen Sie das Spiel auf Steam und klicken Sie erneut auf \"Assets herunterladen\".",
        "alert.openSteamStore": "Steam Store öffnen",
        "alert.close": "Schließen",
        "alert.patchTitle": "Community Patch anwenden?",
        "alert.patchMsg": "Ihre Spieldateien können unwiderruflich verändert oder gelöscht werden.\nDies ist für Online-Spiele erforderlich.",
        "alert.patchButton": "Patch",
        "update.available": "UPDATE VERFÜGBAR: v%@",
        "update.download": "UPDATE HERUNTERLADEN",
        "update.details": "DETAILS ANZEIGEN",
        "footer.author": "Portiert von OKJI (Okladnoj)",
        "steam.status.ready": "BEREIT",
        "steam.status.installingSteamCMD": "STEAMCMD WIRD INSTALLIERT...",
        "steam.status.awaitingCreds": "WARTE AUF ANMELDEDATEN",
        "steam.status.authenticating": "AUTHENTIFIZIERUNG...",
        "steam.status.steamGuard": "STEAM GUARD CODE ERFORDERLICH",
        "steam.status.downloading": "ASSETS WERDEN HERUNTERGELADEN... %@",
        "steam.status.validating": "DATEIEN WERDEN ÜBERPRÜFT...",
        "steam.status.downloadingPatch": "PATCH WIRD HERUNTERGELADEN... %.0f%%",
        "steam.status.unpacking": "PATCH WIRD ENTPACKT...",
        "steam.status.assetsReady": "ASSETS BEREIT",
        "steam.status.error": "FEHLER: %@",
        "patch.status.idle": "WARTE AUF AKTION",
        "patch.status.cleaning": "KONFLIKTDATEIEN WERDEN BEREINIGT...",
        "patch.status.downloading": "PATCH WIRD HERUNTERGELADEN... %.0f%%",
        "patch.status.unpacking": "PATCH WIRD ENTPACKT...",
        "patch.status.completed": "PATCH ERFOLGREICH ANGEWENDET",
        "patch.status.error": "FEHLER: %@",
        "folder.prompt": "Windows-Spielordner auswählen (mit .big-Dateien)",
        "settings.title": "SPIEL-EINSTELLUNGEN",
        "settings.windowedEdgeScroll": "Scrollen am Bildschirmrand im Fenstermodus",
        "settings.windowedEdgeScrollDesc": "Hält den Mauszeiger im Spielfenster, um das Scrollen am Bildschirmrand zu ermöglichen.",
        "settings.language": "Sprache (Language)",
        "settings.about": "System",
        "settings.aboutButton": "Über Generals Online",
        "settings.cameraSection": "Kamera",
        "settings.interfaceSection": "Benutzeroberfläche",
        "settings.showHotkeyLabels": "Tastenkürzel-Buchstaben anzeigen",
        "settings.showHotkeyLabelsDesc": "Zeigt den Tastenkürzel-Buchstaben jedes Befehls auf seinem Symbol in der Befehlsleiste an.",
        "settings.cameraMaxHeight": "Maximale Höhe (Zoom)",
        "settings.cameraMinHeight": "Minimale Höhe (Nah)",
        "settings.cameraSpeed": "Kamerageschwindigkeit",
        "settings.fpsSection": "Leistung",
        "settings.statsOverlay": "FPS & Ping einblenden",
        "settings.limitFps": "Framerate begrenzen",
        "settings.networkSection": "Netzwerk & Protokolle",
        "settings.altEndpoint": "Alternativen Server verwenden",
        "settings.verboseLogging": "Detaillierte Protokollierung",
        "settings.shareLogs": "Logs teilen",
        "settings.shareLogsHint": "Öffnet den Telegram-Chat und die ZIP-Datei — zieh sie in den Chat",
        "settings.shareLogsNone": "Noch keine Log-Dateien gefunden. Aktiviere die detaillierte Protokollierung, starte das Spiel einmal und versuche es erneut.",
        "settings.shareLogsFailed": "Logs konnten nicht gepackt werden. Bitte versuche es erneut.",
        "settings.gameLanguage": "Spielsprache",
        "settings.gameLanguageRestart": "Neustart des Spiels erforderlich",
        "settings.scope.global": "GLOBAL",
        "settings.scope.online": "ONLINE",
        "settings.scope.lobbyHost": "LOBBY-HOST",
        "settings.scope.globalDesc": "GLOBAL: Gilt für alle Spielmodi (Einzelspieler, Gefecht und Online).",
        "settings.scope.onlineDesc": "ONLINE: Funktioniert nur in Multiplayer-Netzwerkmodi.",
        "settings.scope.lobbyHostDesc": "LOBBY-HOST: Gilt nur, wenn Sie eine Multiplayer-Lobby hosten.",
        "settings.legendSection": "LEGENDE",
        "about.windowTitle": "Über Generals Online",
        "about.nativePort": "Nativer macOS-Port",
        "about.portAuthor": "macOS-Port von Dima Ok (OKJI)",
        "about.builtOnTop": "Erstellt auf Basis der EA GPLv3 Open-Source-Version",
        "about.website": "Webseite",
        "about.legal": "C&C: Generals Zero Hour™ ist eine Marke von Electronic Arts.\nSpiel-Engine-Quellcode lizenziert unter GPLv3.",
        "mod.section": "MODS",
        "mod.install": "INSTALLIEREN",
        "mod.repair": "REPARIEREN",
        "mod.installed": "%@ installiert",
        "mod.reinstall": "Neu installieren",
        "mod.remove": "Entfernen",
        "mod.installingTitle": "%@ WIRD INSTALLIERT — BITTE WARTEN",
        "mod.installingHint": "Deine Spiele sind in Ordnung — Start und Patch bleiben gesperrt, damit der Download nicht abbricht",
        "mod.damaged": "%d Datei(en) fehlen — zum Reparieren neu installieren",
        "mod.sizeInfo": "Download %@ · Speicher %@",
        "mod.sizeParts": " · %d Teile",
        "mod.status.notInstalled": "Nicht installiert",
        "mod.status.downloading": "Wird geladen — %d%%",
        "mod.status.downloadingPart": "Teil %d von %d wird geladen — %d%%",
        "mod.status.unpacking": "Wird entpackt",
        "mod.status.unpackingPart": "Teil %d von %d wird entpackt",
        "mod.status.installed": "Installiert",
        "mod.status.error": "Fehler: %@",
        "alert.folderNotSelected": "Es wurde noch kein Spielordner ausgewählt.",
        "alert.binaryNotFound": "%@-Programmdatei nicht gefunden: %@",
        "alert.modFolderMissing": "Mod-Ordner ist nicht verfügbar.",
        "alert.modConfigMissing": "%@ fehlt %@.",
        "alert.launchFailed": "Spiel konnte nicht gestartet werden: %@",
        "sidebar.reset": "ZURÜCKSETZEN",
        "about.version": "Version %@",
        "mod.confirmReinstallTitle": "%@ neu installieren?",
        "mod.confirmReinstallMsg": "Die installierten Dateien werden zuerst gelöscht und erneut heruntergeladen (%@).",
        "mod.confirmRemoveTitle": "%@ entfernen?",
        "mod.confirmRemoveMsg": "Alle installierten Dateien dieser Mod werden gelöscht.",
        "alert.cancel": "Abbrechen",
        "mod.status.removing": "Wird entfernt",
        "mod.removingTitle": "%@ WIRD ENTFERNT — BITTE WARTEN",
        "steam.storedPasswordHint": "Klicken, um das im Schlüsselbund gespeicherte Passwort einzusetzen",
        "steam.usernamePlaceholder": "Steam-Login",
        "steam.passwordPlaceholder": "Passwort eingeben...",
        "steam.storedPasswordTitle": "Gespeichertes Passwort gefunden",
        "steam.storedPasswordMsg": "Für „%@“ liegt ein Passwort im Schlüsselbund. Verwenden oder neu eingeben?",
        "steam.storedPasswordUse": "Verwenden",
        "steam.storedPasswordType": "Selbst eingeben"
    ]

    static let es: [String: String] = [
        "app.title": "GENERALS ONLINE",
        "app.subtitle": "PORT MAC DE LA COMUNIDAD",
        "tab.steam": "STEAM (RECOMENDADO)",
        "tab.local": "ARCHIVO LOCAL",
        "steam.credentials": "CREDENCIALES DE STEAM",
        "steam.submit": "ENVIAR",
        "steam.cancel": "CANCELAR",
        "steam.download": "DESCARGAR RECURSOS",
        "local.path": "RUTA DE DATOS DEL JUEGO:",
        "local.locate": "SELECCIONAR",
        "local.selectHint": "SELECCIONE LA CARPETA PRINCIPAL QUE CONTIENE AMBAS VERSIONES DEL JUEGO",
        "local.invalidTarget": "OBJETIVO INVÁLIDO — No se detectó ini.big / inizh.big en subdirectorios",
        "action.launch": "INICIAR",
        "action.patch": "PARCHE",
        "action.init": "INICIALIZANDO...",
        "alert.launchError": "Error de inicio",
        "alert.ok": "OK",
        "alert.gameNotFound": "Juego no encontrado",
        "alert.gameNotFoundMsg": "La cuenta \"%@\" no posee Command & Conquer™ Generals — Zero Hour.\n\nCompra el juego en Steam y luego presiona \"Descargar recursos\" nuevamente.",
        "alert.openSteamStore": "Abrir Steam Store",
        "alert.close": "Cerrar",
        "alert.patchTitle": "¿Aplicar Community Patch?",
        "alert.patchMsg": "Los archivos del juego pueden ser modificados o eliminados de forma irreversible.\nEsto es necesario para jugar en línea.",
        "alert.patchButton": "Parche",
        "update.available": "ACTUALIZACIÓN DISPONIBLE: v%@",
        "update.download": "DESCARGAR ACTUALIZACIÓN",
        "update.details": "VER DETALLES",
        "footer.author": "Portado por OKJI (Okladnoj)",
        "steam.status.ready": "LISTO",
        "steam.status.installingSteamCMD": "INSTALANDO STEAMCMD...",
        "steam.status.awaitingCreds": "ESPERANDO CREDENCIALES",
        "steam.status.authenticating": "AUTENTICANDO...",
        "steam.status.steamGuard": "CÓDIGO STEAM GUARD REQUERIDO",
        "steam.status.downloading": "DESCARGANDO RECURSOS... %@",
        "steam.status.validating": "VERIFICANDO ARCHIVOS...",
        "steam.status.downloadingPatch": "DESCARGANDO PARCHE... %.0f%%",
        "steam.status.unpacking": "DESCOMPRIMIENDO PARCHE...",
        "steam.status.assetsReady": "RECURSOS LISTOS",
        "steam.status.error": "ERROR: %@",
        "patch.status.idle": "ESPERANDO ACCIÓN",
        "patch.status.cleaning": "LIMPIANDO ARCHIVOS EN CONFLICTO...",
        "patch.status.downloading": "DESCARGANDO PARCHE... %.0f%%",
        "patch.status.unpacking": "DESCOMPRIMIENDO PARCHE...",
        "patch.status.completed": "PARCHE APLICADO CON ÉXITO",
        "patch.status.error": "ERROR: %@",
        "folder.prompt": "Seleccione la carpeta del juego de Windows (que contiene archivos .big)",
        "settings.title": "AJUSTES DEL JUEGO",
        "settings.windowedEdgeScroll": "Desplazamiento en los bordes en modo ventana",
        "settings.windowedEdgeScrollDesc": "Mantiene el cursor dentro de la ventana del juego para permitir el desplazamiento en los bordes.",
        "settings.language": "Idioma (Language)",
        "settings.about": "Sistema",
        "settings.aboutButton": "Acerca de Generals Online",
        "settings.cameraSection": "Cámara",
        "settings.interfaceSection": "Interfaz",
        "settings.showHotkeyLabels": "Mostrar letras de atajos",
        "settings.showHotkeyLabelsDesc": "Muestra la letra del atajo de cada comando en su icono de la barra de comandos.",
        "settings.cameraMaxHeight": "Altura máxima (Zoom)",
        "settings.cameraMinHeight": "Altura mínima (Acercar)",
        "settings.cameraSpeed": "Velocidad de cámara",
        "settings.fpsSection": "Rendimiento",
        "settings.statsOverlay": "Mostrar FPS y Ping",
        "settings.limitFps": "Limitar fotogramas",
        "settings.networkSection": "Red y registros",
        "settings.altEndpoint": "Usar servidor alternativo",
        "settings.verboseLogging": "Registro detallado del motor",
        "settings.shareLogs": "Compartir registros",
        "settings.shareLogsHint": "Abre el chat de Telegram y el ZIP — arrástralo al chat",
        "settings.shareLogsNone": "Aún no se encontraron archivos de registro. Activa el registro detallado del motor, ejecuta el juego una vez y vuelve a intentarlo.",
        "settings.shareLogsFailed": "No se pudieron empaquetar los registros. Inténtalo de nuevo.",
        "settings.gameLanguage": "Idioma del juego",
        "settings.gameLanguageRestart": "Requiere reiniciar el juego",
        "settings.scope.global": "GLOBAL",
        "settings.scope.online": "EN LÍNEA",
        "settings.scope.lobbyHost": "ANFITRIÓN",
        "settings.scope.globalDesc": "GLOBAL: Se aplica a todos los modos de juego (Un jugador, Escaramuza y En línea).",
        "settings.scope.onlineDesc": "EN LÍNEA: Solo funciona en modos de red multijugador.",
        "settings.scope.lobbyHostDesc": "ANFITRIÓN: Solo se aplica al hospedar salas de juego multijugador.",
        "settings.legendSection": "LEYENDA",
        "about.windowTitle": "Acerca de Generals Online",
        "about.nativePort": "Puerto nativo de macOS",
        "about.portAuthor": "Puerto de macOS por Dima Ok (OKJI)",
        "about.builtOnTop": "Creado sobre la versión de código abierto EA GPLv3",
        "about.website": "Sitio web",
        "about.legal": "C&C: Generals Zero Hour™ es una marca comercial de Electronic Arts.\nCódigo fuente del motor de juego bajo licencia GPLv3.",
        "mod.section": "MODS",
        "mod.install": "INSTALAR",
        "mod.repair": "REPARAR",
        "mod.installed": "%@ instalado",
        "mod.reinstall": "Reinstalar",
        "mod.remove": "Eliminar",
        "mod.installingTitle": "INSTALANDO %@ — POR FAVOR ESPERA",
        "mod.installingHint": "Tus juegos están bien — el inicio y el parche quedan bloqueados para no interrumpir la descarga",
        "mod.damaged": "Faltan %d archivo(s) — reinstala para reparar",
        "mod.sizeInfo": "descarga %@ · disco %@",
        "mod.sizeParts": " · %d partes",
        "mod.status.notInstalled": "No instalado",
        "mod.status.downloading": "Descargando — %d%%",
        "mod.status.downloadingPart": "Descargando parte %d de %d — %d%%",
        "mod.status.unpacking": "Descomprimiendo",
        "mod.status.unpackingPart": "Descomprimiendo parte %d de %d",
        "mod.status.installed": "Instalado",
        "mod.status.error": "Error: %@",
        "alert.folderNotSelected": "Aún no se ha seleccionado la carpeta del juego.",
        "alert.binaryNotFound": "No se encontró el ejecutable de %@ en %@",
        "alert.modFolderMissing": "La carpeta del mod no está disponible.",
        "alert.modConfigMissing": "A %@ le falta %@.",
        "alert.launchFailed": "No se pudo iniciar el juego: %@",
        "sidebar.reset": "RESTABLECER",
        "about.version": "Versión %@",
        "mod.confirmReinstallTitle": "¿Reinstalar %@?",
        "mod.confirmReinstallMsg": "Los archivos instalados se eliminarán primero y se descargarán de nuevo (%@).",
        "mod.confirmRemoveTitle": "¿Eliminar %@?",
        "mod.confirmRemoveMsg": "Se eliminarán todos los archivos instalados de este mod.",
        "alert.cancel": "Cancelar",
        "mod.status.removing": "Eliminando",
        "mod.removingTitle": "ELIMINANDO %@ — POR FAVOR ESPERA",
        "steam.storedPasswordHint": "Haz clic para insertar la contraseña guardada en el llavero",
        "steam.usernamePlaceholder": "Usuario de Steam",
        "steam.passwordPlaceholder": "Introduce la contraseña...",
        "steam.storedPasswordTitle": "Contraseña guardada encontrada",
        "steam.storedPasswordMsg": "Hay una contraseña para «%@» en el llavero. ¿Usarla o escribir otra?",
        "steam.storedPasswordUse": "Usar guardada",
        "steam.storedPasswordType": "Escribir a mano"
    ]

    static let tr: [String: String] = [
        "app.title": "GENERALS ONLINE",
        "app.subtitle": "TOPLULUK MAC PORTU",
        "tab.steam": "STEAM (ÖNERİLEN)",
        "tab.local": "YEREL ARŞİV",
        "steam.credentials": "STEAM KİMLİK BİLGİLERİ",
        "steam.submit": "GÖNDER",
        "steam.cancel": "İPTAL",
        "steam.download": "KAYNAKLARI İNDİR",
        "local.path": "OYUN VERİ YOLU:",
        "local.locate": "SEÇ",
        "local.selectHint": "HER İKİ OYUN SÜRÜMÜNÜ İÇEREN ANA KLASÖRÜ SEÇİN",
        "local.invalidTarget": "GEÇERSİZ HEDEF — Alt dizinlerde ini.big / inizh.big tespit edilemedi",
        "action.launch": "BAŞLAT",
        "action.patch": "YAMA",
        "action.init": "BAŞLATILIYOR...",
        "alert.launchError": "Başlatma Hatası",
        "alert.ok": "Tamam",
        "alert.gameNotFound": "Oyun Bulunamadı",
        "alert.gameNotFoundMsg": "\"%@\" hesabı Command & Conquer™ Generals — Zero Hour'a sahip değil.\n\nOyunu Steam'den satın alın, ardından tekrar \"Kaynakları İndir\" düğmesine basın.",
        "alert.openSteamStore": "Steam Mağazasını Aç",
        "alert.close": "Kapat",
        "alert.patchTitle": "Community Patch Uygulanacak mı?",
        "alert.patchMsg": "Oyun dosyalarınız geri dönüşü olmayacak şekilde değiştirilebilir veya silinebilir.\nÇevrimiçi oynamak için bu gereklidir.",
        "alert.patchButton": "Yama",
        "update.available": "GÜNCELLEME MEVCUT: v%@",
        "update.download": "GÜNCELLEMEYİ İNDİR",
        "update.details": "DETAYLARI GÖR",
        "footer.author": "Port: OKJI (Okladnoj)",
        "steam.status.ready": "HAZIR",
        "steam.status.installingSteamCMD": "STEAMCMD KURULUYOR...",
        "steam.status.awaitingCreds": "KİMLİK BİLGİLERİ BEKLENİYOR",
        "steam.status.authenticating": "KİMLİK DOĞRULAMA...",
        "steam.status.steamGuard": "STEAM GUARD KODU GEREKLİ",
        "steam.status.downloading": "KAYNAKLAR İNDİRİLİYOR... %@",
        "steam.status.validating": "DOSYALAR DOĞRULANIYOR...",
        "steam.status.downloadingPatch": "YAMA İNDİRİLİYOR... %.0f%%",
        "steam.status.unpacking": "YAMA AÇILIYOR...",
        "steam.status.assetsReady": "KAYNAKLAR HAZIR",
        "steam.status.error": "HATA: %@",
        "patch.status.idle": "EYLEM BEKLENİYOR",
        "patch.status.cleaning": "ÇAKIŞAN DOSYALAR TEMİZLENİYOR...",
        "patch.status.downloading": "YAMA İNDİRİLİYOR... %.0f%%",
        "patch.status.unpacking": "YAMA AÇILIYOR...",
        "patch.status.completed": "YAMA BAŞARIYLA UYGULANDI",
        "patch.status.error": "HATA: %@",
        "folder.prompt": "Windows oyun klasörünü seçin (.big dosyaları içeren)",
        "settings.title": "OYUN AYARLARI",
        "settings.windowedEdgeScroll": "Pencere Modunda Kenar Kaydırma",
        "settings.windowedEdgeScrollDesc": "Kenar kaydırma için oyun sırasında fare imlecini pencere sınırları içinde tutar.",
        "settings.language": "Dil (Language)",
        "settings.about": "Sistem",
        "settings.aboutButton": "Generals Online Hakkında",
        "settings.cameraSection": "Kamera",
        "settings.interfaceSection": "Arayüz",
        "settings.showHotkeyLabels": "Kısayol Harflerini Göster",
        "settings.showHotkeyLabelsDesc": "Her komutun kısayol harfini komut çubuğundaki simgesinde gösterir.",
        "settings.cameraMaxHeight": "Maks. Yükseklik (Zoom)",
        "settings.cameraMinHeight": "Min. Yükseklik (Yakınlaşma)",
        "settings.cameraSpeed": "Kamera Hızı",
        "settings.fpsSection": "Performans",
        "settings.statsOverlay": "FPS ve Ping Göstergesini Aç",
        "settings.limitFps": "Kare Hızını Sınırla",
        "settings.networkSection": "Ağ ve Günlükler",
        "settings.altEndpoint": "Alternatif Sunucu Kullan",
        "settings.verboseLogging": "Ayrıntılı Motor Günlüğü",
        "settings.shareLogs": "Günlükleri paylaş",
        "settings.shareLogsHint": "Telegram sohbetini ve ZIP dosyasını açar — sohbete sürükleyin",
        "settings.shareLogsNone": "Henüz günlük dosyası bulunamadı. Ayrıntılı motor günlüğünü etkinleştirin, oyunu bir kez çalıştırın ve tekrar deneyin.",
        "settings.shareLogsFailed": "Günlükler paketlenemedi. Lütfen tekrar deneyin.",
        "settings.gameLanguage": "Oyun Dili",
        "settings.gameLanguageRestart": "Oyunun yeniden başlatılması gerekiyor",
        "settings.scope.global": "GENEL",
        "settings.scope.online": "ÇEVRİMİÇİ",
        "settings.scope.lobbyHost": "LOBİ SAHİBİ",
        "settings.scope.globalDesc": "GENEL: Tüm oyun modları için geçerlidir (Tek Oyunculu, Çatışma ve Çevrimiçi).",
        "settings.scope.onlineDesc": "ÇEVRİMİÇİ: Yalnızca çok oyunculu ağ modlarında çalışır.",
        "settings.scope.lobbyHostDesc": "LOBİ SAHİBİ: Yalnızca çok oyunculu lobileri kurduğunuzda geçerlidir.",
        "settings.legendSection": "AÇIKLAMA",
        "about.windowTitle": "Generals Online Hakkında",
        "about.nativePort": "macOS Yerel Portu",
        "about.portAuthor": "macOS Portu: Dima Ok (OKJI)",
        "about.builtOnTop": "EA GPLv3 açık kaynak sürümü temel alınarak oluşturulmuştur",
        "about.website": "Web Sitesi",
        "about.legal": "C&C: Generals Zero Hour™ Electronic Arts'ın ticari markasıdır.\nOyun motoru kaynak kodu GPLv3 lisanslıdır.",
        "mod.section": "MODLAR",
        "mod.install": "KUR",
        "mod.repair": "ONAR",
        "mod.installed": "%@ kuruldu",
        "mod.reinstall": "Yeniden kur",
        "mod.remove": "Kaldır",
        "mod.installingTitle": "%@ KURULUYOR — LÜTFEN BEKLEYİN",
        "mod.installingHint": "Oyunlarınız güvende — indirme kesilmesin diye başlatma ve yama kilitli tutuluyor",
        "mod.damaged": "%d dosya eksik — onarmak için yeniden kurun",
        "mod.sizeInfo": "indirme %@ · disk %@",
        "mod.sizeParts": " · %d parça",
        "mod.status.notInstalled": "Kurulu değil",
        "mod.status.downloading": "İndiriliyor — %%%d",
        "mod.status.downloadingPart": "Parça %d/%d indiriliyor — %%%d",
        "mod.status.unpacking": "Açılıyor",
        "mod.status.unpackingPart": "Parça %d/%d açılıyor",
        "mod.status.installed": "Kuruldu",
        "mod.status.error": "Hata: %@",
        "alert.folderNotSelected": "Oyun klasörü henüz seçilmedi.",
        "alert.binaryNotFound": "%@ çalıştırılabilir dosyası bulunamadı: %@",
        "alert.modFolderMissing": "Mod klasörü kullanılamıyor.",
        "alert.modConfigMissing": "%@ içinde %@ eksik.",
        "alert.launchFailed": "Oyun başlatılamadı: %@",
        "sidebar.reset": "SIFIRLA",
        "about.version": "Sürüm %@",
        "mod.confirmReinstallTitle": "%@ yeniden kurulsun mu?",
        "mod.confirmReinstallMsg": "Kurulu dosyalar önce silinecek ve yeniden indirilecek (%@).",
        "mod.confirmRemoveTitle": "%@ kaldırılsın mı?",
        "mod.confirmRemoveMsg": "Bu modun kurulu tüm dosyaları silinecek.",
        "alert.cancel": "İptal",
        "mod.status.removing": "Kaldırılıyor",
        "mod.removingTitle": "%@ KALDIRILIYOR — LÜTFEN BEKLEYİN",
        "steam.storedPasswordHint": "Anahtar zincirinde kayıtlı parolayı doldurmak için tıklayın",
        "steam.usernamePlaceholder": "Steam kullanıcı adı",
        "steam.passwordPlaceholder": "Parolayı girin...",
        "steam.storedPasswordTitle": "Kayıtlı parola bulundu",
        "steam.storedPasswordMsg": "“%@” için anahtar zincirinde bir parola var. Kullanılsın mı, yoksa yenisi mi girilsin?",
        "steam.storedPasswordUse": "Kayıtlıyı kullan",
        "steam.storedPasswordType": "Elle gir"
    ]
}
